const P = 'awswaf:managed:aws:bot-control:';

export interface LabelEntry {
  label: string;
  displayName: string;
  description?: string;
}

export interface DynamicLabelEntry {
  prefix: string;
  displayName: string;
  placeholder: string;
  description?: string;
}

export interface LabelCategory {
  name: string;
  labels: LabelEntry[];
  dynamicLabels?: DynamicLabelEntry[];
}

export interface NamespaceEntry {
  namespace: string;
  displayName: string;
  description?: string;
}

export const labelCategories: LabelCategory[] = [
  {
    name: 'Bot Verification Status',
    labels: [
      { label: `${P}bot:verified`, displayName: 'Verified Bot', description: 'Bot that self-identifies and is independently verified' },
      { label: `${P}bot:unverified`, displayName: 'Unverified Bot', description: 'Bot that self-identifies but cannot be verified' },
      { label: `${P}bot:user_triggered:verified`, displayName: 'User-Triggered Bot (verified)', description: 'Verified bot invoked by end users' },
      { label: `${P}bot:developer_platform:verified`, displayName: 'Developer Platform Bot (verified)', description: 'Verified bot from dev platforms (e.g. Google Apps Script)' },
    ],
  },
  {
    name: 'Bot Category',
    labels: [
      { label: `${P}bot:category:ai`, displayName: 'AI Bot' },
      { label: `${P}bot:category:search_engine`, displayName: 'Search Engine' },
      { label: `${P}bot:category:content_fetcher`, displayName: 'Content Fetcher' },
      { label: `${P}bot:category:social_media`, displayName: 'Social Media' },
      { label: `${P}bot:category:advertising`, displayName: 'Advertising' },
      { label: `${P}bot:category:archiver`, displayName: 'Archiver' },
      { label: `${P}bot:category:seo`, displayName: 'SEO' },
      { label: `${P}bot:category:scraping_framework`, displayName: 'Scraping Framework' },
      { label: `${P}bot:category:http_library`, displayName: 'HTTP Library' },
      { label: `${P}bot:category:security`, displayName: 'Security' },
      { label: `${P}bot:category:monitoring`, displayName: 'Monitoring' },
      { label: `${P}bot:category:link_checker`, displayName: 'Link Checker' },
      { label: `${P}bot:category:email_client`, displayName: 'Email Client' },
      { label: `${P}bot:category:page_preview`, displayName: 'Page Preview' },
      { label: `${P}bot:category:webhooks`, displayName: 'Webhooks' },
      { label: `${P}bot:category:miscellaneous`, displayName: 'Miscellaneous' },
    ],
  },
  {
    name: 'Bot Names',
    labels: [
    { label: `${P}bot:name:2checkout`, displayName: '2Checkout' },
    { label: `${P}bot:name:360monitoring`, displayName: '360Monitoring' },
    { label: `${P}bot:name:360spider`, displayName: '360Spider' },
    { label: `${P}bot:name:aasa_bot`, displayName: 'Aasa Bot' },
    { label: `${P}bot:name:abcdatos`, displayName: 'Abcdatos' },
    { label: `${P}bot:name:accessstatus`, displayName: 'Accessstatus' },
    { label: `${P}bot:name:accoona`, displayName: 'Accoona' },
    { label: `${P}bot:name:acme_spider`, displayName: 'Acme Spider' },
    { label: `${P}bot:name:acquia_optimize_monsido`, displayName: 'Acquia Optimize Monsido' },
    { label: `${P}bot:name:activecomply_bot`, displayName: 'Activecomply Bot' },
    { label: `${P}bot:name:acunetix`, displayName: 'Acunetix' },
    { label: `${P}bot:name:adagiobot`, displayName: 'Adagiobot' },
    { label: `${P}bot:name:addthis`, displayName: 'Addthis' },
    { label: `${P}bot:name:adidxbot`, displayName: 'Adidxbot' },
    { label: `${P}bot:name:admantx`, displayName: 'Admantx' },
    { label: `${P}bot:name:adstxtcrawler`, displayName: 'Adstxtcrawler' },
    { label: `${P}bot:name:adyen`, displayName: 'Adyen' },
    { label: `${P}bot:name:affiliate_crawler`, displayName: 'Affiliate Crawler' },
    { label: `${P}bot:name:aftership_magento_2`, displayName: 'Aftership Magento 2' },
    { label: `${P}bot:name:agency_analytics_crawler`, displayName: 'Agency Analytics Crawler' },
    { label: `${P}bot:name:ahrefsbot`, displayName: 'Ahrefsbot' },
    { label: `${P}bot:name:ahrefssiteaudit`, displayName: 'Ahrefssiteaudit' },
    { label: `${P}bot:name:akismet`, displayName: 'Akismet' },
    { label: `${P}bot:name:alertsite`, displayName: 'Alertsite' },
    { label: `${P}bot:name:alexabot`, displayName: 'Alexabot' },
    { label: `${P}bot:name:algolia`, displayName: 'Algolia' },
    { label: `${P}bot:name:allafrica_crawler`, displayName: 'Allafrica Crawler' },
    { label: `${P}bot:name:almaden`, displayName: 'Almaden' },
    { label: `${P}bot:name:amazon_adbot`, displayName: 'Amazon Adbot' },
    { label: `${P}bot:name:amazon_contxtbot`, displayName: 'Amazon Contxtbot' },
    { label: `${P}bot:name:amazon_kendra`, displayName: 'Amazon Kendra' },
    { label: `${P}bot:name:amazon_product_discovery`, displayName: 'Amazon Product Discovery' },
    { label: `${P}bot:name:amazonauditbot`, displayName: 'Amazonauditbot' },
    { label: `${P}bot:name:amazonauditbot_mobile`, displayName: 'Amazonauditbot Mobile' },
    { label: `${P}bot:name:amazonauditspider`, displayName: 'Amazonauditspider' },
    { label: `${P}bot:name:amazonbot`, displayName: 'AmazonBot' },
    { label: `${P}bot:name:android_programmatic_http_client`, displayName: 'Android Programmatic Http Client' },
    { label: `${P}bot:name:anthropic`, displayName: 'Anthropic' },
    { label: `${P}bot:name:apache`, displayName: 'Apache' },
    { label: `${P}bot:name:app_insights`, displayName: 'App Insights' },
    { label: `${P}bot:name:appengine`, displayName: 'Appengine' },
    { label: `${P}bot:name:applebot`, displayName: 'AppleBot' },
    { label: `${P}bot:name:applebot_extended`, displayName: 'AppleBot Extended' },
    { label: `${P}bot:name:architext`, displayName: 'Architext' },
    { label: `${P}bot:name:area_360`, displayName: 'Area 360' },
    { label: `${P}bot:name:artemis_web_reader`, displayName: 'Artemis Web Reader' },
    { label: `${P}bot:name:asurioncrawler`, displayName: 'Asurioncrawler' },
    { label: `${P}bot:name:atomz`, displayName: 'Atomz' },
    { label: `${P}bot:name:attracta`, displayName: 'Attracta' },
    { label: `${P}bot:name:audisto_crawler`, displayName: 'Audisto Crawler' },
    { label: `${P}bot:name:authory`, displayName: 'Authory' },
    { label: `${P}bot:name:automaton`, displayName: 'Automaton' },
    { label: `${P}bot:name:automattic_tumblr`, displayName: 'Automattic Tumblr' },
    { label: `${P}bot:name:avantgo`, displayName: 'Avantgo' },
    { label: `${P}bot:name:awario`, displayName: 'Awario' },
    { label: `${P}bot:name:axios`, displayName: 'Axios' },
    { label: `${P}bot:name:baidu`, displayName: 'Baidu' },
    { label: `${P}bot:name:baiduspidermobile`, displayName: 'Baiduspidermobile' },
    { label: `${P}bot:name:barkrowler`, displayName: 'Barkrowler' },
    { label: `${P}bot:name:bazqux`, displayName: 'Bazqux' },
    { label: `${P}bot:name:bdfetch`, displayName: 'Bdfetch' },
    { label: `${P}bot:name:bedrockbot`, displayName: 'BedrockBot' },
    { label: `${P}bot:name:bestchange_bot`, displayName: 'Bestchange Bot' },
    { label: `${P}bot:name:better_uptime`, displayName: 'Better Uptime' },
    { label: `${P}bot:name:bibliotheque_nacional_de_france`, displayName: 'Bibliotheque Nacional De France' },
    { label: `${P}bot:name:big_sur_ai`, displayName: 'Big Sur Ai' },
    { label: `${P}bot:name:bigupdatabot`, displayName: 'Bigupdatabot' },
    { label: `${P}bot:name:binarycanary`, displayName: 'Binarycanary' },
    { label: `${P}bot:name:bingbot`, displayName: 'Bingbot' },
    { label: `${P}bot:name:bitbucket`, displayName: 'Bitbucket' },
    { label: `${P}bot:name:bitly`, displayName: 'Bitly' },
    { label: `${P}bot:name:black_duck_fast_dynamic`, displayName: 'Black Duck Fast Dynamic' },
    { label: `${P}bot:name:blexbot`, displayName: 'Blexbot' },
    { label: `${P}bot:name:bling_erp`, displayName: 'Bling Erp' },
    { label: `${P}bot:name:blinkx`, displayName: 'Blinkx' },
    { label: `${P}bot:name:blockaid`, displayName: 'Blockaid' },
    { label: `${P}bot:name:blogtrottr`, displayName: 'Blogtrottr' },
    { label: `${P}bot:name:blogvault`, displayName: 'Blogvault' },
    { label: `${P}bot:name:bluesky_app`, displayName: 'Bluesky App' },
    { label: `${P}bot:name:boardgameprices_bot`, displayName: 'Boardgameprices Bot' },
    { label: `${P}bot:name:bomborabot`, displayName: 'Bomborabot' },
    { label: `${P}bot:name:boneybadgerbot`, displayName: 'Boneybadgerbot' },
    { label: `${P}bot:name:book_searcher`, displayName: 'Book Searcher' },
    { label: `${P}bot:name:booko`, displayName: 'Booko' },
    { label: `${P}bot:name:bordermanager`, displayName: 'Bordermanager' },
    { label: `${P}bot:name:botify`, displayName: 'Botify' },
    { label: `${P}bot:name:brand_verity`, displayName: 'Brand Verity' },
    { label: `${P}bot:name:brightedgebot`, displayName: 'Brightedgebot' },
    { label: `${P}bot:name:bugsnag`, displayName: 'Bugsnag' },
    { label: `${P}bot:name:bushbaby`, displayName: 'Bushbaby' },
    { label: `${P}bot:name:buttondown_rss_feed_parser`, displayName: 'Buttondown Rss Feed Parser' },
    { label: `${P}bot:name:bytespider`, displayName: 'ByteSpider' },
    { label: `${P}bot:name:caliperbot`, displayName: 'Caliperbot' },
    { label: `${P}bot:name:camelhttpstream`, displayName: 'Camelhttpstream' },
    { label: `${P}bot:name:capitalonebot`, displayName: 'Capitalonebot' },
    { label: `${P}bot:name:catchpoint`, displayName: 'Catchpoint' },
    { label: `${P}bot:name:ccbot`, displayName: 'CCBot' },
    { label: `${P}bot:name:censys`, displayName: 'Censys' },
    { label: `${P}bot:name:cert_chief`, displayName: 'Cert Chief' },
    { label: `${P}bot:name:cf_digicert_dcv`, displayName: 'Cf Digicert Dcv' },
    { label: `${P}bot:name:channable_importer`, displayName: 'Channable Importer' },
    { label: `${P}bot:name:chargebee`, displayName: 'Chargebee' },
    { label: `${P}bot:name:chatgpt`, displayName: 'ChatGPT' },
    { label: `${P}bot:name:chatgpt_user`, displayName: 'ChatGPT User' },
    { label: `${P}bot:name:checkbot`, displayName: 'Checkbot' },
    { label: `${P}bot:name:checkly`, displayName: 'Checkly' },
    { label: `${P}bot:name:checkmark_network`, displayName: 'Checkmark Network' },
    { label: `${P}bot:name:chrome_lighthouse`, displayName: 'Chrome Lighthouse' },
    { label: `${P}bot:name:claude_user`, displayName: 'Claude User' },
    { label: `${P}bot:name:claude_web`, displayName: 'Claude Web' },
    { label: `${P}bot:name:claudebot`, displayName: 'ClaudeBot' },
    { label: `${P}bot:name:clickagy`, displayName: 'Clickagy' },
    { label: `${P}bot:name:cliqzbot`, displayName: 'Cliqzbot' },
    { label: `${P}bot:name:cloudflare`, displayName: 'Cloudflare' },
    { label: `${P}bot:name:cloudtrellis`, displayName: 'Cloudtrellis' },
    { label: `${P}bot:name:cludobot`, displayName: 'Cludobot' },
    { label: `${P}bot:name:coccoc`, displayName: 'Coccoc' },
    { label: `${P}bot:name:cognitiveseo`, displayName: 'Cognitiveseo' },
    { label: `${P}bot:name:cohere`, displayName: 'Cohere' },
    { label: `${P}bot:name:coinbase`, displayName: 'Coinbase' },
    { label: `${P}bot:name:comodo`, displayName: 'Comodo' },
    { label: `${P}bot:name:contentking`, displayName: 'Contentking' },
    { label: `${P}bot:name:convermaxbot`, displayName: 'Convermaxbot' },
    { label: `${P}bot:name:cookie_hub`, displayName: 'Cookie Hub' },
    { label: `${P}bot:name:cookiebot`, displayName: 'Cookiebot' },
    { label: `${P}bot:name:cookiemaestro`, displayName: 'Cookiemaestro' },
    { label: `${P}bot:name:cotoyogi`, displayName: 'Cotoyogi' },
    { label: `${P}bot:name:coveobot`, displayName: 'Coveobot' },
    { label: `${P}bot:name:cozi_icalendar`, displayName: 'Cozi Icalendar' },
    { label: `${P}bot:name:crawler4j`, displayName: 'Crawler4J' },
    { label: `${P}bot:name:crawlson`, displayName: 'Crawlson' },
    { label: `${P}bot:name:crazy_egg_bot`, displayName: 'Crazy Egg Bot' },
    { label: `${P}bot:name:criteobot`, displayName: 'Criteobot' },
    { label: `${P}bot:name:criticalcssbot`, displayName: 'Criticalcssbot' },
    { label: `${P}bot:name:cronjob`, displayName: 'Cronjob' },
    { label: `${P}bot:name:curl`, displayName: 'Curl' },
    { label: `${P}bot:name:cxensebot`, displayName: 'Cxensebot' },
    { label: `${P}bot:name:cydralspider`, displayName: 'Cydralspider' },
    { label: `${P}bot:name:datadog_synthetic_monitor`, displayName: 'Datadog Synthetic Monitor' },
    { label: `${P}bot:name:dataforseo_siteauditor`, displayName: 'Dataforseo Siteauditor' },
    { label: `${P}bot:name:dataforseobot`, displayName: 'Dataforseobot' },
    { label: `${P}bot:name:datanyze`, displayName: 'Datanyze' },
    { label: `${P}bot:name:dataprovider_com`, displayName: 'Dataprovider Com' },
    { label: `${P}bot:name:datenbank`, displayName: 'Datenbank' },
    { label: `${P}bot:name:daum`, displayName: 'Daum' },
    { label: `${P}bot:name:deepcrawl`, displayName: 'Deepcrawl' },
    { label: `${P}bot:name:detectify`, displayName: 'Detectify' },
    { label: `${P}bot:name:devin`, displayName: 'Devin' },
    { label: `${P}bot:name:diffbot`, displayName: 'Diffbot' },
    { label: `${P}bot:name:digext`, displayName: 'Digext' },
    { label: `${P}bot:name:digicert_dcv`, displayName: 'Digicert Dcv' },
    { label: `${P}bot:name:discordbot`, displayName: 'Discordbot' },
    { label: `${P}bot:name:docomo`, displayName: 'Docomo' },
    { label: `${P}bot:name:dotbot`, displayName: 'Dotbot' },
    { label: `${P}bot:name:dotcom_monitor`, displayName: 'Dotcom Monitor' },
    { label: `${P}bot:name:doubleverify`, displayName: 'Doubleverify' },
    { label: `${P}bot:name:drlinkcheck`, displayName: 'Drlinkcheck' },
    { label: `${P}bot:name:drupal`, displayName: 'Drupal' },
    { label: `${P}bot:name:duckassistbot`, displayName: 'DuckAssistBot' },
    { label: `${P}bot:name:duckduckbot`, displayName: 'Duckduckbot' },
    { label: `${P}bot:name:duckduckgo_favicons_bot`, displayName: 'Duckduckgo Favicons Bot' },
    { label: `${P}bot:name:easybill_import_manager`, displayName: 'Easybill Import Manager' },
    { label: `${P}bot:name:easycron`, displayName: 'Easycron' },
    { label: `${P}bot:name:easydns`, displayName: 'Easydns' },
    { label: `${P}bot:name:echoboxbot`, displayName: 'Echoboxbot' },
    { label: `${P}bot:name:elmahio_uptimebot`, displayName: 'Elmahio Uptimebot' },
    { label: `${P}bot:name:email_marketing_high_priority`, displayName: 'Email Marketing High Priority' },
    { label: `${P}bot:name:email_marketing_low_priority`, displayName: 'Email Marketing Low Priority' },
    { label: `${P}bot:name:embedly`, displayName: 'Embedly' },
    { label: `${P}bot:name:emcspider`, displayName: 'Emcspider' },
    { label: `${P}bot:name:emoneybot`, displayName: 'Emoneybot' },
    { label: `${P}bot:name:epivoz_crawler`, displayName: 'Epivoz Crawler' },
    { label: `${P}bot:name:erepublik_tools`, displayName: 'Erepublik Tools' },
    { label: `${P}bot:name:etaospider`, displayName: 'Etaospider' },
    { label: `${P}bot:name:evensi`, displayName: 'Evensi' },
    { label: `${P}bot:name:eventmachine`, displayName: 'Eventmachine' },
    { label: `${P}bot:name:evo_uptime_bot`, displayName: 'Evo Uptime Bot' },
    { label: `${P}bot:name:exabot_thumbnails`, displayName: 'Exabot Thumbnails' },
    { label: `${P}bot:name:exodus_movement`, displayName: 'Exodus Movement' },
    { label: `${P}bot:name:ezoicbot`, displayName: 'Ezoicbot' },
    { label: `${P}bot:name:ezooms`, displayName: 'Ezooms' },
    { label: `${P}bot:name:facebook`, displayName: 'Facebook' },
    { label: `${P}bot:name:facebook_bot`, displayName: 'Facebook Bot' },
    { label: `${P}bot:name:facebot`, displayName: 'Facebot' },
    { label: `${P}bot:name:factset_spyderbot`, displayName: 'Factset Spyderbot' },
    { label: `${P}bot:name:fake_ie60_java`, displayName: 'Fake Ie60 Java' },
    { label: `${P}bot:name:fastenterprise`, displayName: 'Fastenterprise' },
    { label: `${P}bot:name:fasthttp`, displayName: 'FastHTTP' },
    { label: `${P}bot:name:fastmail_bot`, displayName: 'Fastmail Bot' },
    { label: `${P}bot:name:fastwebcrawler`, displayName: 'Fastwebcrawler' },
    { label: `${P}bot:name:fdl_stats_bot`, displayName: 'Fdl Stats Bot' },
    { label: `${P}bot:name:fedreporter_bot_for_ffiec`, displayName: 'Fedreporter Bot For Ffiec' },
    { label: `${P}bot:name:feedbin`, displayName: 'Feedbin' },
    { label: `${P}bot:name:feedburner`, displayName: 'Feedburner' },
    { label: `${P}bot:name:feeder`, displayName: 'Feeder' },
    { label: `${P}bot:name:feedfinder`, displayName: 'Feedfinder' },
    { label: `${P}bot:name:feedly`, displayName: 'Feedly' },
    { label: `${P}bot:name:feedspot`, displayName: 'Feedspot' },
    { label: `${P}bot:name:feedwind`, displayName: 'Feedwind' },
    { label: `${P}bot:name:fetch`, displayName: 'Fetch' },
    { label: `${P}bot:name:findlinks`, displayName: 'Findlinks' },
    { label: `${P}bot:name:flipboard`, displayName: 'Flipboard' },
    { label: `${P}bot:name:foregenix_threatview_webscan`, displayName: 'Foregenix Threatview Webscan' },
    { label: `${P}bot:name:freespoke`, displayName: 'Freespoke' },
    { label: `${P}bot:name:freshpingbot`, displayName: 'Freshpingbot' },
    { label: `${P}bot:name:fullstorybot`, displayName: 'Fullstorybot' },
    { label: `${P}bot:name:funnelback`, displayName: 'Funnelback' },
    { label: `${P}bot:name:garlik`, displayName: 'Garlik' },
    { label: `${P}bot:name:gemini_deep_research`, displayName: 'Gemini Deep Research' },
    { label: `${P}bot:name:generic_crawler`, displayName: 'Generic Crawler' },
    { label: `${P}bot:name:generic_search_bot`, displayName: 'Generic Search Bot' },
    { label: `${P}bot:name:genieo`, displayName: 'Genieo' },
    { label: `${P}bot:name:getintent`, displayName: 'Getintent' },
    { label: `${P}bot:name:ghost_inspector`, displayName: 'Ghost Inspector' },
    { label: `${P}bot:name:gigabot`, displayName: 'Gigabot' },
    { label: `${P}bot:name:go_http`, displayName: 'Go Http' },
    { label: `${P}bot:name:gomez`, displayName: 'Gomez' },
    { label: `${P}bot:name:google_adsbot`, displayName: 'Google Adsbot' },
    { label: `${P}bot:name:google_adsense`, displayName: 'Google Adsense' },
    { label: `${P}bot:name:google_adwords_express`, displayName: 'Google Adwords Express' },
    { label: `${P}bot:name:google_adwords_instant`, displayName: 'Google Adwords Instant' },
    { label: `${P}bot:name:google_apis`, displayName: 'Google Apis' },
    { label: `${P}bot:name:google_app_engine`, displayName: 'Google App Engine' },
    { label: `${P}bot:name:google_apps_script`, displayName: 'Google Apps Script' },
    { label: `${P}bot:name:google_association_service`, displayName: 'Google Association Service' },
    { label: `${P}bot:name:google_cloud_vertex_bot`, displayName: 'Google Cloud Vertex Bot' },
    { label: `${P}bot:name:google_common_crawler`, displayName: 'Google Common Crawler' },
    { label: `${P}bot:name:google_favicon`, displayName: 'Google Favicon' },
    { label: `${P}bot:name:google_feedfetcher`, displayName: 'Google Feedfetcher' },
    { label: `${P}bot:name:google_http_java_client`, displayName: 'Google Http Java Client' },
    { label: `${P}bot:name:google_imageproxy`, displayName: 'Google Imageproxy' },
    { label: `${P}bot:name:google_inspection_tool`, displayName: 'Google Inspection Tool' },
    { label: `${P}bot:name:google_lighthouse`, displayName: 'Google Lighthouse' },
    { label: `${P}bot:name:google_mediapartners`, displayName: 'Google Mediapartners' },
    { label: `${P}bot:name:google_other`, displayName: 'Google Other' },
    { label: `${P}bot:name:google_pagerenderer`, displayName: 'Google Pagerenderer' },
    { label: `${P}bot:name:google_publisher_center`, displayName: 'Google Publisher Center' },
    { label: `${P}bot:name:google_read_aloud`, displayName: 'Google Read Aloud' },
    { label: `${P}bot:name:google_safety`, displayName: 'Google Safety' },
    { label: `${P}bot:name:google_scholar`, displayName: 'Google Scholar' },
    { label: `${P}bot:name:google_site_verification`, displayName: 'Google Site Verification' },
    { label: `${P}bot:name:google_special_case_crawler`, displayName: 'Google Special Case Crawler' },
    { label: `${P}bot:name:google_storebot`, displayName: 'Google Storebot' },
    { label: `${P}bot:name:google_trust_services`, displayName: 'Google Trust Services' },
    { label: `${P}bot:name:google_user_triggered_fetcher`, displayName: 'Google User Triggered Fetcher' },
    { label: `${P}bot:name:google_web_preview`, displayName: 'Google Web Preview' },
    { label: `${P}bot:name:googlebot`, displayName: 'Googlebot' },
    { label: `${P}bot:name:googlebot_ezweb_mobile`, displayName: 'Googlebot Ezweb Mobile' },
    { label: `${P}bot:name:googlebotadwordsmobile`, displayName: 'Googlebotadwordsmobile' },
    { label: `${P}bot:name:googlebotimage`, displayName: 'Googlebotimage' },
    { label: `${P}bot:name:googlebotimages`, displayName: 'Googlebotimages' },
    { label: `${P}bot:name:googlebotmobile`, displayName: 'Googlebotmobile' },
    { label: `${P}bot:name:googlebotsimple`, displayName: 'Googlebotsimple' },
    { label: `${P}bot:name:googlebotvideos`, displayName: 'Googlebotvideos' },
    { label: `${P}bot:name:googledata`, displayName: 'Googledata' },
    { label: `${P}bot:name:googlesearchappliance`, displayName: 'Googlesearchappliance' },
    { label: `${P}bot:name:googleweblight`, displayName: 'Googleweblight' },
    { label: `${P}bot:name:googlewebmastertools`, displayName: 'Googlewebmastertools' },
    { label: `${P}bot:name:gopay`, displayName: 'Gopay' },
    { label: `${P}bot:name:gptbot`, displayName: 'GPTBot' },
    { label: `${P}bot:name:grafana_labs`, displayName: 'Grafana Labs' },
    { label: `${P}bot:name:grapeshot`, displayName: 'Grapeshot' },
    { label: `${P}bot:name:groovinads`, displayName: 'Groovinads' },
    { label: `${P}bot:name:grub`, displayName: 'Grub' },
    { label: `${P}bot:name:gsitecrawler`, displayName: 'Gsitecrawler' },
    { label: `${P}bot:name:gtmetrix`, displayName: 'Gtmetrix' },
    { label: `${P}bot:name:guestpostsbot`, displayName: 'Guestpostsbot' },
    { label: `${P}bot:name:gulperbot`, displayName: 'Gulperbot' },
    { label: `${P}bot:name:guzzle`, displayName: 'Guzzle' },
    { label: `${P}bot:name:harvester`, displayName: 'Harvester' },
    { label: `${P}bot:name:hatena`, displayName: 'Hatena' },
    { label: `${P}bot:name:hellowork_bot`, displayName: 'Hellowork Bot' },
    { label: `${P}bot:name:helpfeel_notabot`, displayName: 'Helpfeel Notabot' },
    { label: `${P}bot:name:heritrix`, displayName: 'Heritrix' },
    { label: `${P}bot:name:hetrixtools`, displayName: 'Hetrixtools' },
    { label: `${P}bot:name:hifibot`, displayName: 'Hifibot' },
    { label: `${P}bot:name:hiongun`, displayName: 'Hiongun' },
    { label: `${P}bot:name:hosttracker`, displayName: 'Hosttracker' },
    { label: `${P}bot:name:hstspreload_bot`, displayName: 'Hstspreload Bot' },
    { label: `${P}bot:name:httplite`, displayName: 'Httplite' },
    { label: `${P}bot:name:httprequester`, displayName: 'Httprequester' },
    { label: `${P}bot:name:hubspot`, displayName: 'Hubspot' },
    { label: `${P}bot:name:hubspot_feed_fetcher`, displayName: 'Hubspot Feed Fetcher' },
    { label: `${P}bot:name:hubspot_page_fetcher`, displayName: 'Hubspot Page Fetcher' },
    { label: `${P}bot:name:huckabot`, displayName: 'Huckabot' },
    { label: `${P}bot:name:hypemachine`, displayName: 'Hypemachine' },
    { label: `${P}bot:name:ias_crawler`, displayName: 'Ias Crawler' },
    { label: `${P}bot:name:ichiro`, displayName: 'Ichiro' },
    { label: `${P}bot:name:iframely`, displayName: 'Iframely' },
    { label: `${P}bot:name:ifttt_rss_feed_service`, displayName: 'Ifttt Rss Feed Service' },
    { label: `${P}bot:name:imagesift`, displayName: 'ImageSift' },
    { label: `${P}bot:name:imessage_preview`, displayName: 'iMessage Preview' },
    { label: `${P}bot:name:inktomi_slurp`, displayName: 'Inktomi Slurp' },
    { label: `${P}bot:name:innguma_fetcher`, displayName: 'Innguma Fetcher' },
    { label: `${P}bot:name:innologica`, displayName: 'Innologica' },
    { label: `${P}bot:name:instapaper`, displayName: 'Instapaper' },
    { label: `${P}bot:name:integromatbot`, displayName: 'Integromatbot' },
    { label: `${P}bot:name:internet_archive`, displayName: 'Internet Archive' },
    { label: `${P}bot:name:ipworks`, displayName: 'Ipworks' },
    { label: `${P}bot:name:isdownbot`, displayName: 'Isdownbot' },
    { label: `${P}bot:name:isecbot`, displayName: 'Isecbot' },
    { label: `${P}bot:name:jagged_pixel_uptime`, displayName: 'Jagged Pixel Uptime' },
    { label: `${P}bot:name:jakarta`, displayName: 'Jakarta' },
    { label: `${P}bot:name:java`, displayName: 'Java' },
    { label: `${P}bot:name:javahttpclient`, displayName: 'Javahttpclient' },
    { label: `${P}bot:name:jersey`, displayName: 'Jersey' },
    { label: `${P}bot:name:jetpack`, displayName: 'Jetpack' },
    { label: `${P}bot:name:jobswithgptcom_bot`, displayName: 'Jobswithgptcom Bot' },
    { label: `${P}bot:name:jumio`, displayName: 'Jumio' },
    { label: `${P}bot:name:kagi`, displayName: 'Kagi' },
    { label: `${P}bot:name:kargobot_artemis`, displayName: 'Kargobot Artemis' },
    { label: `${P}bot:name:kinsta_bot`, displayName: 'Kinsta Bot' },
    { label: `${P}bot:name:klaviyo`, displayName: 'Klaviyo' },
    { label: `${P}bot:name:legalmonster`, displayName: 'Legalmonster' },
    { label: `${P}bot:name:letsencrypt`, displayName: 'Letsencrypt' },
    { label: `${P}bot:name:level_9_search_bot`, displayName: 'Level 9 Search Bot' },
    { label: `${P}bot:name:libhttp`, displayName: 'Libhttp' },
    { label: `${P}bot:name:libperl`, displayName: 'Libperl' },
    { label: `${P}bot:name:library_of_congress_web_archiving`, displayName: 'Library Of Congress Web Archiving' },
    { label: `${P}bot:name:linespider`, displayName: 'Linespider' },
    { label: `${P}bot:name:linguee`, displayName: 'Linguee' },
    { label: `${P}bot:name:linkchecker`, displayName: 'Linkchecker' },
    { label: `${P}bot:name:linkdex`, displayName: 'Linkdex' },
    { label: `${P}bot:name:linkedin`, displayName: 'Linkedin' },
    { label: `${P}bot:name:linklint`, displayName: 'Linklint' },
    { label: `${P}bot:name:linkscan`, displayName: 'Linkscan' },
    { label: `${P}bot:name:linksindexerbot`, displayName: 'Linksindexerbot' },
    { label: `${P}bot:name:linksmanager`, displayName: 'Linksmanager' },
    { label: `${P}bot:name:linktiger`, displayName: 'Linktiger' },
    { label: `${P}bot:name:linkup`, displayName: 'Linkup' },
    { label: `${P}bot:name:linkwalker`, displayName: 'Linkwalker' },
    { label: `${P}bot:name:livedoor`, displayName: 'Livedoor' },
    { label: `${P}bot:name:livedoor_feedfetcher`, displayName: 'Livedoor Feedfetcher' },
    { label: `${P}bot:name:livelapbot`, displayName: 'Livelapbot' },
    { label: `${P}bot:name:logicmonitor`, displayName: 'Logicmonitor' },
    { label: `${P}bot:name:loomlybot`, displayName: 'Loomlybot' },
    { label: `${P}bot:name:lydia`, displayName: 'Lydia' },
    { label: `${P}bot:name:macrobondbot`, displayName: 'Macrobondbot' },
    { label: `${P}bot:name:magibot`, displayName: 'Magibot' },
    { label: `${P}bot:name:magnetmebot`, displayName: 'Magnetmebot' },
    { label: `${P}bot:name:magpie`, displayName: 'Magpie' },
    { label: `${P}bot:name:mailru`, displayName: 'Mailru' },
    { label: `${P}bot:name:mainwp`, displayName: 'Mainwp' },
    { label: `${P}bot:name:make_platform`, displayName: 'Make Platform' },
    { label: `${P}bot:name:managewp`, displayName: 'Managewp' },
    { label: `${P}bot:name:marfeel`, displayName: 'Marfeel' },
    { label: `${P}bot:name:marginaliabot`, displayName: 'Marginaliabot' },
    { label: `${P}bot:name:marketgoo`, displayName: 'Marketgoo' },
    { label: `${P}bot:name:mars_finder`, displayName: 'Mars Finder' },
    { label: `${P}bot:name:mauibot`, displayName: 'Mauibot' },
    { label: `${P}bot:name:maverick`, displayName: 'Maverick' },
    { label: `${P}bot:name:mavifinds_bot`, displayName: 'Mavifinds Bot' },
    { label: `${P}bot:name:media_monitoring_bot`, displayName: 'Media Monitoring Bot' },
    { label: `${P}bot:name:medialogiabot`, displayName: 'Medialogiabot' },
    { label: `${P}bot:name:mediatoolkitbot`, displayName: 'Mediatoolkitbot' },
    { label: `${P}bot:name:mediavine_metadata_parser`, displayName: 'Mediavine Metadata Parser' },
    { label: `${P}bot:name:megaindex`, displayName: 'Megaindex' },
    { label: `${P}bot:name:melonmesabot`, displayName: 'Melonmesabot' },
    { label: `${P}bot:name:meta-externalads`, displayName: 'Meta External Ads' },
    { label: `${P}bot:name:meta-externalagent`, displayName: 'Meta External Agent' },
    { label: `${P}bot:name:meta-externalfetcher`, displayName: 'Meta External Fetcher' },
    { label: `${P}bot:name:meta-webindexer`, displayName: 'Meta Web Indexer' },
    { label: `${P}bot:name:metaexternalagent`, displayName: 'MetaExternalAgent' },
    { label: `${P}bot:name:metauri`, displayName: 'Metauri' },
    { label: `${P}bot:name:metorik`, displayName: 'Metorik' },
    { label: `${P}bot:name:mgidbot`, displayName: 'Mgidbot' },
    { label: `${P}bot:name:microsoft_preview`, displayName: 'Microsoft Preview' },
    { label: `${P}bot:name:miniflux`, displayName: 'Miniflux' },
    { label: `${P}bot:name:mirrorwebcrawler`, displayName: 'Mirrorwebcrawler' },
    { label: `${P}bot:name:missinglettrbot`, displayName: 'Missinglettrbot' },
    { label: `${P}bot:name:mistralai_user`, displayName: 'MistralAI User' },
    { label: `${P}bot:name:mixi_check`, displayName: 'Mixi Check' },
    { label: `${P}bot:name:mixrankbot`, displayName: 'Mixrankbot' },
    { label: `${P}bot:name:mj12bot`, displayName: 'Mj12Bot' },
    { label: `${P}bot:name:mnogosearch`, displayName: 'Mnogosearch' },
    { label: `${P}bot:name:moatbot`, displayName: 'Moatbot' },
    { label: `${P}bot:name:modular_ds`, displayName: 'Modular Ds' },
    { label: `${P}bot:name:mojeek`, displayName: 'Mojeek' },
    { label: `${P}bot:name:molliebot`, displayName: 'Molliebot' },
    { label: `${P}bot:name:momspider`, displayName: 'Momspider' },
    { label: `${P}bot:name:mon_spark`, displayName: 'Mon Spark' },
    { label: `${P}bot:name:monitis`, displayName: 'Monitis' },
    { label: `${P}bot:name:monitorss`, displayName: 'Monitorss' },
    { label: `${P}bot:name:montasticmonitor`, displayName: 'Montasticmonitor' },
    { label: `${P}bot:name:moodlebot`, displayName: 'Moodlebot' },
    { label: `${P}bot:name:motominerbot`, displayName: 'Motominerbot' },
    { label: `${P}bot:name:mrgbot`, displayName: 'Mrgbot' },
    { label: `${P}bot:name:msnbot`, displayName: 'Msnbot' },
    { label: `${P}bot:name:mushilabs_clearscopebot`, displayName: 'Mushilabs Clearscopebot' },
    { label: `${P}bot:name:naver`, displayName: 'Naver' },
    { label: `${P}bot:name:naver_ads`, displayName: 'Naver Ads' },
    { label: `${P}bot:name:naver_preview`, displayName: 'Naver Preview' },
    { label: `${P}bot:name:neevabot`, displayName: 'Neevabot' },
    { label: `${P}bot:name:netcraft`, displayName: 'Netcraft' },
    { label: `${P}bot:name:netumo`, displayName: 'Netumo' },
    { label: `${P}bot:name:netvibes`, displayName: 'Netvibes' },
    { label: `${P}bot:name:netvigie`, displayName: 'Netvigie' },
    { label: `${P}bot:name:never_converting_netscape`, displayName: 'Never Converting Netscape' },
    { label: `${P}bot:name:new_york_times_newsgathering`, displayName: 'New York Times Newsgathering' },
    { label: `${P}bot:name:newrelic`, displayName: 'Newrelic' },
    { label: `${P}bot:name:newrelic_synthetic_monitor`, displayName: 'Newrelic Synthetic Monitor' },
    { label: `${P}bot:name:news_blur`, displayName: 'News Blur' },
    { label: `${P}bot:name:newsnow`, displayName: 'Newsnow' },
    { label: `${P}bot:name:newspaper`, displayName: 'Newspaper' },
    { label: `${P}bot:name:nimbostratus`, displayName: 'Nimbostratus' },
    { label: `${P}bot:name:nitro`, displayName: 'Nitro' },
    { label: `${P}bot:name:nixstats`, displayName: 'Nixstats' },
    { label: `${P}bot:name:node_fetch`, displayName: 'Node Fetch' },
    { label: `${P}bot:name:nodeping`, displayName: 'Nodeping' },
    { label: `${P}bot:name:noibu`, displayName: 'Noibu' },
    { label: `${P}bot:name:nokia_jumpbot_mobile`, displayName: 'Nokia Jumpbot Mobile' },
    { label: `${P}bot:name:noorobot`, displayName: 'Noorobot' },
    { label: `${P}bot:name:nooshub`, displayName: 'Nooshub' },
    { label: `${P}bot:name:nova_act`, displayName: 'Nova Act' },
    { label: `${P}bot:name:ntt_docomo_foma_crawler`, displayName: 'Ntt Docomo Foma Crawler' },
    { label: `${P}bot:name:ntt_docomo_mova_crawler`, displayName: 'Ntt Docomo Mova Crawler' },
    { label: `${P}bot:name:ntt_docomo_yahoo_au_crawler`, displayName: 'Ntt Docomo Yahoo Au Crawler' },
    { label: `${P}bot:name:ntt_docomo_yahoo_docomo_crawler`, displayName: 'Ntt Docomo Yahoo Docomo Crawler' },
    { label: `${P}bot:name:ntt_docomo_yahoo_softbank_crawler`, displayName: 'Ntt Docomo Yahoo Softbank Crawler' },
    { label: `${P}bot:name:nytimes`, displayName: 'NYTimes' },
    { label: `${P}bot:name:objectssearch`, displayName: 'Objectssearch' },
    { label: `${P}bot:name:ohdear`, displayName: 'Ohdear' },
    { label: `${P}bot:name:okhttp`, displayName: 'Okhttp' },
    { label: `${P}bot:name:omgili`, displayName: 'Omgili' },
    { label: `${P}bot:name:omnisend`, displayName: 'Omnisend' },
    { label: `${P}bot:name:oncrawl`, displayName: 'Oncrawl' },
    { label: `${P}bot:name:onetrust_cmp_scanner`, displayName: 'Onetrust Cmp Scanner' },
    { label: `${P}bot:name:online_webceo_bot`, displayName: 'Online Webceo Bot' },
    { label: `${P}bot:name:onlineornot`, displayName: 'Onlineornot' },
    { label: `${P}bot:name:ontospider`, displayName: 'Ontospider' },
    { label: `${P}bot:name:opengraphbot`, displayName: 'Opengraphbot' },
    { label: `${P}bot:name:openrss`, displayName: 'Openrss' },
    { label: `${P}bot:name:oracleultrasearch`, displayName: 'Oracleultrasearch' },
    { label: `${P}bot:name:orlo_link_preview`, displayName: 'Orlo Link Preview' },
    { label: `${P}bot:name:outbrain`, displayName: 'Outbrain' },
    { label: `${P}bot:name:outlook`, displayName: 'Outlook' },
    { label: `${P}bot:name:outsell_url_validator`, displayName: 'Outsell Url Validator' },
    { label: `${P}bot:name:overcast`, displayName: 'Overcast' },
    { label: `${P}bot:name:ozon_web_grabber`, displayName: 'Ozon Web Grabber' },
    { label: `${P}bot:name:pandalytics`, displayName: 'Pandalytics' },
    { label: `${P}bot:name:panopta`, displayName: 'Panopta' },
    { label: `${P}bot:name:paperlibot`, displayName: 'Paperlibot' },
    { label: `${P}bot:name:parsely`, displayName: 'Parsely' },
    { label: `${P}bot:name:paypal`, displayName: 'Paypal' },
    { label: `${P}bot:name:pci_qualys`, displayName: 'Pci Qualys' },
    { label: `${P}bot:name:pdns_monitor`, displayName: 'Pdns Monitor' },
    { label: `${P}bot:name:pear_php`, displayName: 'Pear Php' },
    { label: `${P}bot:name:perplexity-user`, displayName: 'Perplexity User' },
    { label: `${P}bot:name:perplexitybot`, displayName: 'PerplexityBot' },
    { label: `${P}bot:name:petalbot`, displayName: 'Petalbot' },
    { label: `${P}bot:name:phpcrawl`, displayName: 'Phpcrawl' },
    { label: `${P}bot:name:pingability`, displayName: 'Pingability' },
    { label: `${P}bot:name:pingdom`, displayName: 'Pingdom' },
    { label: `${P}bot:name:pingping`, displayName: 'Pingping' },
    { label: `${P}bot:name:pinterest`, displayName: 'Pinterest' },
    { label: `${P}bot:name:pocket`, displayName: 'Pocket' },
    { label: `${P}bot:name:pocketcasts_feed_parser`, displayName: 'Pocketcasts Feed Parser' },
    { label: `${P}bot:name:poe`, displayName: 'Poe' },
    { label: `${P}bot:name:potions`, displayName: 'Potions' },
    { label: `${P}bot:name:prerender`, displayName: 'Prerender' },
    { label: `${P}bot:name:press_engine_bot`, displayName: 'Press Engine Bot' },
    { label: `${P}bot:name:printfriendly`, displayName: 'Printfriendly' },
    { label: `${P}bot:name:pro_sitemaps`, displayName: 'Pro Sitemaps' },
    { label: `${P}bot:name:proctorio`, displayName: 'Proctorio' },
    { label: `${P}bot:name:project_honeypot`, displayName: 'Project Honeypot' },
    { label: `${P}bot:name:project_shield_urlcheck`, displayName: 'Project Shield Urlcheck' },
    { label: `${P}bot:name:protopage`, displayName: 'Protopage' },
    { label: `${P}bot:name:proximic`, displayName: 'Proximic' },
    { label: `${P}bot:name:prtg`, displayName: 'Prtg' },
    { label: `${P}bot:name:psbot`, displayName: 'Psbot' },
    { label: `${P}bot:name:pulsetic`, displayName: 'Pulsetic' },
    { label: `${P}bot:name:pwabuilder`, displayName: 'Pwabuilder' },
    { label: `${P}bot:name:python`, displayName: 'Python' },
    { label: `${P}bot:name:python_requests`, displayName: 'Python Requests' },
    { label: `${P}bot:name:qualifiedbot`, displayName: 'Qualifiedbot' },
    { label: `${P}bot:name:qualys`, displayName: 'Qualys' },
    { label: `${P}bot:name:quantcastbot`, displayName: 'Quantcastbot' },
    { label: `${P}bot:name:queryseekerspider`, displayName: 'Queryseekerspider' },
    { label: `${P}bot:name:quorabot`, displayName: 'Quorabot' },
    { label: `${P}bot:name:qwantify`, displayName: 'Qwantify' },
    { label: `${P}bot:name:rackspace`, displayName: 'Rackspace' },
    { label: `${P}bot:name:rakutenusabot_image`, displayName: 'Rakutenusabot Image' },
    { label: `${P}bot:name:readable`, displayName: 'Readable' },
    { label: `${P}bot:name:redditbot`, displayName: 'Redditbot' },
    { label: `${P}bot:name:reelevant`, displayName: 'Reelevant' },
    { label: `${P}bot:name:retool`, displayName: 'Retool' },
    { label: `${P}bot:name:retrolistecom`, displayName: 'Retrolistecom' },
    { label: `${P}bot:name:revvim`, displayName: 'Revvim' },
    { label: `${P}bot:name:reward_gateway`, displayName: 'Reward Gateway' },
    { label: `${P}bot:name:riddler`, displayName: 'Riddler' },
    { label: `${P}bot:name:rigor`, displayName: 'Rigor' },
    { label: `${P}bot:name:rogerbot`, displayName: 'Rogerbot' },
    { label: `${P}bot:name:route53_health_check`, displayName: 'Route53 Health Check' },
    { label: `${P}bot:name:rss2tg_bot`, displayName: 'Rss2Tg Bot' },
    { label: `${P}bot:name:rssapi`, displayName: 'Rssapi' },
    { label: `${P}bot:name:ruby`, displayName: 'Ruby' },
    { label: `${P}bot:name:sae`, displayName: 'Sae' },
    { label: `${P}bot:name:salesforce`, displayName: 'Salesforce' },
    { label: `${P}bot:name:salesviewer`, displayName: 'Salesviewer' },
    { label: `${P}bot:name:scanalert`, displayName: 'Scanalert' },
    { label: `${P}bot:name:scanpower`, displayName: 'Scanpower' },
    { label: `${P}bot:name:schmozilla`, displayName: 'Schmozilla' },
    { label: `${P}bot:name:scour_rss_bot`, displayName: 'Scour Rss Bot' },
    { label: `${P}bot:name:scrapy`, displayName: 'Scrapy' },
    { label: `${P}bot:name:se_ranking_bot`, displayName: 'Se Ranking Bot' },
    { label: `${P}bot:name:searchatlas_bot`, displayName: 'Searchatlas Bot' },
    { label: `${P}bot:name:searchbot`, displayName: 'SearchBot' },
    { label: `${P}bot:name:securityheaders`, displayName: 'Securityheaders' },
    { label: `${P}bot:name:seekportbot`, displayName: 'Seekportbot' },
    { label: `${P}bot:name:semanticscholarbot`, displayName: 'Semanticscholarbot' },
    { label: `${P}bot:name:semrush_siteauditbot`, displayName: 'Semrush Siteauditbot' },
    { label: `${P}bot:name:semrushbot`, displayName: 'Semrushbot' },
    { label: `${P}bot:name:sendgrid`, displayName: 'Sendgrid' },
    { label: `${P}bot:name:sentibot`, displayName: 'Sentibot' },
    { label: `${P}bot:name:sentry`, displayName: 'Sentry' },
    { label: `${P}bot:name:sentry_uptime_monitoring`, displayName: 'Sentry Uptime Monitoring' },
    { label: `${P}bot:name:seo4ajax`, displayName: 'Seo4Ajax' },
    { label: `${P}bot:name:seo_audit_check_bot`, displayName: 'Seo Audit Check Bot' },
    { label: `${P}bot:name:seobilitybot`, displayName: 'Seobilitybot' },
    { label: `${P}bot:name:sequelwpbpt`, displayName: 'Sequelwpbpt' },
    { label: `${P}bot:name:serpstatbot`, displayName: 'Serpstatbot' },
    { label: `${P}bot:name:serverdensity`, displayName: 'Serverdensity' },
    { label: `${P}bot:name:serverhunter`, displayName: 'Serverhunter' },
    { label: `${P}bot:name:seznam`, displayName: 'Seznam' },
    { label: `${P}bot:name:shopify_captain_hook`, displayName: 'Shopify Captain Hook' },
    { label: `${P}bot:name:shortwave_image_fetcher`, displayName: 'Shortwave Image Fetcher' },
    { label: `${P}bot:name:siege`, displayName: 'Siege' },
    { label: `${P}bot:name:silktidebot`, displayName: 'Silktidebot' },
    { label: `${P}bot:name:similar_tech`, displayName: 'Similar Tech' },
    { label: `${P}bot:name:sistrixcrawler`, displayName: 'Sistrixcrawler' },
    { label: `${P}bot:name:site24x7`, displayName: 'Site24X7' },
    { label: `${P}bot:name:site_improve`, displayName: 'Site Improve' },
    { label: `${P}bot:name:site_search_360`, displayName: 'Site Search 360' },
    { label: `${P}bot:name:sitecheck_sitecrawl`, displayName: 'Sitecheck Sitecrawl' },
    { label: `${P}bot:name:siteimprove_linkcheck`, displayName: 'Siteimprove Linkcheck' },
    { label: `${P}bot:name:sitelock`, displayName: 'Sitelock' },
    { label: `${P}bot:name:siteuptime`, displayName: 'Siteuptime' },
    { label: `${P}bot:name:skroutzbot`, displayName: 'Skroutzbot' },
    { label: `${P}bot:name:skroutzimagebot`, displayName: 'Skroutzimagebot' },
    { label: `${P}bot:name:skypeuripreview`, displayName: 'Skypeuripreview' },
    { label: `${P}bot:name:slack_images`, displayName: 'Slack Images' },
    { label: `${P}bot:name:slackbot`, displayName: 'Slackbot' },
    { label: `${P}bot:name:slackbotlinkexpanding`, displayName: 'Slackbotlinkexpanding' },
    { label: `${P}bot:name:slickstream`, displayName: 'Slickstream' },
    { label: `${P}bot:name:smartologybot`, displayName: 'Smartologybot' },
    { label: `${P}bot:name:smtnetpmbot`, displayName: 'Smtnetpmbot' },
    { label: `${P}bot:name:snapchat`, displayName: 'Snapchat' },
    { label: `${P}bot:name:snipcart`, displayName: 'Snipcart' },
    { label: `${P}bot:name:snoopy`, displayName: 'Snoopy' },
    { label: `${P}bot:name:sogou`, displayName: 'Sogou' },
    { label: `${P}bot:name:solarwinds_observability`, displayName: 'Solarwinds Observability' },
    { label: `${P}bot:name:sora_caisse_pos`, displayName: 'Sora Caisse Pos' },
    { label: `${P}bot:name:sosospider`, displayName: 'Sosospider' },
    { label: `${P}bot:name:spark_shipping`, displayName: 'Spark Shipping' },
    { label: `${P}bot:name:sparkpost`, displayName: 'Sparkpost' },
    { label: `${P}bot:name:spectate`, displayName: 'Spectate' },
    { label: `${P}bot:name:splunk_attack_analyzer`, displayName: 'Splunk Attack Analyzer' },
    { label: `${P}bot:name:splunk_synthetics`, displayName: 'Splunk Synthetics' },
    { label: `${P}bot:name:stape_scanner`, displayName: 'Stape Scanner' },
    { label: `${P}bot:name:statabot`, displayName: 'Statabot' },
    { label: `${P}bot:name:statistikaustria`, displayName: 'Statistikaustria' },
    { label: `${P}bot:name:statsdronebot`, displayName: 'Statsdronebot' },
    { label: `${P}bot:name:statuscake`, displayName: 'Statuscake' },
    { label: `${P}bot:name:steam_chat`, displayName: 'Steam Chat' },
    { label: `${P}bot:name:steeler`, displayName: 'Steeler' },
    { label: `${P}bot:name:strata2crawler`, displayName: 'Strata2Crawler' },
    { label: `${P}bot:name:stripe`, displayName: 'Stripe' },
    { label: `${P}bot:name:study_partner`, displayName: 'Study Partner' },
    { label: `${P}bot:name:sumologic`, displayName: 'Sumologic' },
    { label: `${P}bot:name:superfeedr`, displayName: 'Superfeedr' },
    { label: `${P}bot:name:taboolabot`, displayName: 'Taboolabot' },
    { label: `${P}bot:name:telegram`, displayName: 'Telegram' },
    { label: `${P}bot:name:tiktok`, displayName: 'TikTok' },
    { label: `${P}bot:name:timpibot`, displayName: 'TimpiBot' },
    { label: `${P}bot:name:tin_eye`, displayName: 'Tin Eye' },
    { label: `${P}bot:name:tiny_rss`, displayName: 'Tiny Rss' },
    { label: `${P}bot:name:trendictionbot`, displayName: 'Trendictionbot' },
    { label: `${P}bot:name:twitter`, displayName: 'Twitter' },
    { label: `${P}bot:name:uptimerobot`, displayName: 'Uptimerobot' },
    { label: `${P}bot:name:w3c`, displayName: 'W3C' },
    { label: `${P}bot:name:w3c_validation_services`, displayName: 'W3C Validation Services' },
    { label: `${P}bot:name:wappalyzer`, displayName: 'Wappalyzer' },
    { label: `${P}bot:name:web_copier`, displayName: 'Web Copier' },
    { label: `${P}bot:name:wget`, displayName: 'Wget' },
    { label: `${P}bot:name:whatsapp`, displayName: 'Whatsapp' },
    { label: `${P}bot:name:wordpress_scanner`, displayName: 'Wordpress Scanner' },
    { label: `${P}bot:name:yacy`, displayName: 'Yacy' },
    { label: `${P}bot:name:yahoo`, displayName: 'Yahoo' },
    { label: `${P}bot:name:yahoo_mail`, displayName: 'Yahoo Mail' },
    { label: `${P}bot:name:yandexbot`, displayName: 'Yandexbot' },
    { label: `${P}bot:name:yanga`, displayName: 'Yanga' },
    { label: `${P}bot:name:yisouspider`, displayName: 'YisouSpider' },
    { label: `${P}bot:name:zyborg`, displayName: 'Zyborg' },
    ],
  },
  {
    name: 'Bot Organizations',
    labels: [
    { label: `${P}bot:organization:acquia`, displayName: 'Acquia' },
    { label: `${P}bot:organization:adyen`, displayName: 'Adyen' },
    { label: `${P}bot:organization:agencyanalytics`, displayName: 'Agencyanalytics' },
    { label: `${P}bot:organization:ahrefs`, displayName: 'Ahrefs' },
    { label: `${P}bot:organization:airo`, displayName: 'Airo' },
    { label: `${P}bot:organization:algolia`, displayName: 'Algolia' },
    { label: `${P}bot:organization:amazon`, displayName: 'Amazon' },
    { label: `${P}bot:organization:anthropic`, displayName: 'Anthropic' },
    { label: `${P}bot:organization:apple`, displayName: 'Apple' },
    { label: `${P}bot:organization:atlassian`, displayName: 'Atlassian' },
    { label: `${P}bot:organization:audisto`, displayName: 'Audisto' },
    { label: `${P}bot:organization:automattic`, displayName: 'Automattic' },
    { label: `${P}bot:organization:baidu`, displayName: 'Baidu' },
    { label: `${P}bot:organization:betterstack`, displayName: 'Betterstack' },
    { label: `${P}bot:organization:blogvault`, displayName: 'Blogvault' },
    { label: `${P}bot:organization:brandwatch`, displayName: 'Brandwatch' },
    { label: `${P}bot:organization:buttondown`, displayName: 'Buttondown' },
    { label: `${P}bot:organization:bytedance`, displayName: 'ByteDance' },
    { label: `${P}bot:organization:capjamesg`, displayName: 'Capjamesg' },
    { label: `${P}bot:organization:censys`, displayName: 'Censys' },
    { label: `${P}bot:organization:cludo`, displayName: 'Cludo' },
    { label: `${P}bot:organization:cognition`, displayName: 'Cognition' },
    { label: `${P}bot:organization:common_crawl`, displayName: 'Common Crawl' },
    { label: `${P}bot:organization:comscore`, displayName: 'Comscore' },
    { label: `${P}bot:organization:cookiehub`, displayName: 'Cookiehub' },
    { label: `${P}bot:organization:criteo`, displayName: 'Criteo' },
    { label: `${P}bot:organization:datadog`, displayName: 'Datadog' },
    { label: `${P}bot:organization:dataforseo`, displayName: 'Dataforseo' },
    { label: `${P}bot:organization:designmodo`, displayName: 'Designmodo' },
    { label: `${P}bot:organization:digicert`, displayName: 'Digicert' },
    { label: `${P}bot:organization:duckduckgo`, displayName: 'DuckDuckGo' },
    { label: `${P}bot:organization:easycron`, displayName: 'Easycron' },
    { label: `${P}bot:organization:elmahio`, displayName: 'Elmahio' },
    { label: `${P}bot:organization:facebook`, displayName: 'Facebook' },
    { label: `${P}bot:organization:feedbin`, displayName: 'Feedbin' },
    { label: `${P}bot:organization:flipboard`, displayName: 'Flipboard' },
    { label: `${P}bot:organization:foxhound_systems`, displayName: 'Foxhound Systems' },
    { label: `${P}bot:organization:godaddy`, displayName: 'Godaddy' },
    { label: `${P}bot:organization:google`, displayName: 'Google' },
    { label: `${P}bot:organization:hetrixtools`, displayName: 'Hetrixtools' },
    { label: `${P}bot:organization:host-tracker`, displayName: 'Host Tracker' },
    { label: `${P}bot:organization:huawei`, displayName: 'Huawei' },
    { label: `${P}bot:organization:hubspot`, displayName: 'HubSpot' },
    { label: `${P}bot:organization:huckabuy`, displayName: 'Huckabuy' },
    { label: `${P}bot:organization:immutable`, displayName: 'Immutable' },
    { label: `${P}bot:organization:incsub`, displayName: 'Incsub' },
    { label: `${P}bot:organization:isdown`, displayName: 'Isdown' },
    { label: `${P}bot:organization:jumio`, displayName: 'Jumio' },
    { label: `${P}bot:organization:kagiinc`, displayName: 'Kagiinc' },
    { label: `${P}bot:organization:kalpraj_solutions`, displayName: 'Kalpraj Solutions' },
    { label: `${P}bot:organization:line`, displayName: 'Line' },
    { label: `${P}bot:organization:lumar`, displayName: 'Lumar' },
    { label: `${P}bot:organization:magnetme`, displayName: 'Magnetme' },
    { label: `${P}bot:organization:majestic`, displayName: 'Majestic' },
    { label: `${P}bot:organization:make`, displayName: 'Make' },
    { label: `${P}bot:organization:marfeel`, displayName: 'Marfeel' },
    { label: `${P}bot:organization:marginaliasearch`, displayName: 'Marginaliasearch' },
    { label: `${P}bot:organization:medialogia`, displayName: 'Medialogia' },
    { label: `${P}bot:organization:mediamonitoringbot`, displayName: 'Mediamonitoringbot' },
    { label: `${P}bot:organization:microsoft`, displayName: 'Microsoft' },
    { label: `${P}bot:organization:monspark`, displayName: 'Monspark' },
    { label: `${P}bot:organization:motominer`, displayName: 'Motominer' },
    { label: `${P}bot:organization:mozilla`, displayName: 'Mozilla' },
    { label: `${P}bot:organization:mushi_labs`, displayName: 'Mushi Labs' },
    { label: `${P}bot:organization:naver`, displayName: 'Naver' },
    { label: `${P}bot:organization:new_relic`, displayName: 'New Relic' },
    { label: `${P}bot:organization:newsblur`, displayName: 'Newsblur' },
    { label: `${P}bot:organization:nitropack`, displayName: 'Nitropack' },
    { label: `${P}bot:organization:nodeping`, displayName: 'Nodeping' },
    { label: `${P}bot:organization:nytimes`, displayName: 'Nytimes' },
    { label: `${P}bot:organization:omnisend`, displayName: 'Omnisend' },
    { label: `${P}bot:organization:oncrawl`, displayName: 'Oncrawl' },
    { label: `${P}bot:organization:openai`, displayName: 'OpenAI' },
    { label: `${P}bot:organization:oracle`, displayName: 'Oracle' },
    { label: `${P}bot:organization:paypal`, displayName: 'PayPal' },
    { label: `${P}bot:organization:perplexity`, displayName: 'Perplexity' },
    { label: `${P}bot:organization:pinterest`, displayName: 'Pinterest' },
    { label: `${P}bot:organization:pressengine`, displayName: 'Pressengine' },
    { label: `${P}bot:organization:pro_sitemaps`, displayName: 'Pro Sitemaps' },
    { label: `${P}bot:organization:probely`, displayName: 'Probely' },
    { label: `${P}bot:organization:qualified`, displayName: 'Qualified' },
    { label: `${P}bot:organization:qualys`, displayName: 'Qualys' },
    { label: `${P}bot:organization:quantcast`, displayName: 'Quantcast' },
    { label: `${P}bot:organization:qwant`, displayName: 'Qwant' },
    { label: `${P}bot:organization:raptive`, displayName: 'Raptive' },
    { label: `${P}bot:organization:realify`, displayName: 'Realify' },
    { label: `${P}bot:organization:retool`, displayName: 'Retool' },
    { label: `${P}bot:organization:rois`, displayName: 'Rois' },
    { label: `${P}bot:organization:saasgroup`, displayName: 'Saasgroup' },
    { label: `${P}bot:organization:se_ranking`, displayName: 'Se Ranking' },
    { label: `${P}bot:organization:seekport`, displayName: 'Seekport' },
    { label: `${P}bot:organization:semrush`, displayName: 'Semrush' },
    { label: `${P}bot:organization:sentry`, displayName: 'Sentry' },
    { label: `${P}bot:organization:serverhunter`, displayName: 'Serverhunter' },
    { label: `${P}bot:organization:seznam`, displayName: 'Seznam' },
    { label: `${P}bot:organization:siteimprove`, displayName: 'Siteimprove' },
    { label: `${P}bot:organization:siteuptime`, displayName: 'Siteuptime' },
    { label: `${P}bot:organization:skroutz`, displayName: 'Skroutz' },
    { label: `${P}bot:organization:slack`, displayName: 'Slack' },
    { label: `${P}bot:organization:smartbear`, displayName: 'Smartbear' },
    { label: `${P}bot:organization:snap`, displayName: 'Snap' },
    { label: `${P}bot:organization:sogou`, displayName: 'Sogou' },
    { label: `${P}bot:organization:solarwinds`, displayName: 'Solarwinds' },
    { label: `${P}bot:organization:sspworks`, displayName: 'Sspworks' },
    { label: `${P}bot:organization:stape`, displayName: 'Stape' },
    { label: `${P}bot:organization:stripe`, displayName: 'Stripe' },
    { label: `${P}bot:organization:sureswiftcapital`, displayName: 'Sureswiftcapital' },
    { label: `${P}bot:organization:svix`, displayName: 'Svix' },
    { label: `${P}bot:organization:synopsys`, displayName: 'Synopsys' },
    { label: `${P}bot:organization:taboola`, displayName: 'Taboola' },
    { label: `${P}bot:organization:telegram`, displayName: 'Telegram' },
    { label: `${P}bot:organization:the_trade_desk`, displayName: 'The Trade Desk' },
    { label: `${P}bot:organization:updown`, displayName: 'Updown' },
    { label: `${P}bot:organization:uptimia`, displayName: 'Uptimia' },
    { label: `${P}bot:organization:uptrends`, displayName: 'Uptrends' },
    { label: `${P}bot:organization:w3c`, displayName: 'W3C' },
    { label: `${P}bot:organization:ward`, displayName: 'Ward' },
    { label: `${P}bot:organization:watchful`, displayName: 'Watchful' },
    { label: `${P}bot:organization:webceo`, displayName: 'Webceo' },
    { label: `${P}bot:organization:webpros`, displayName: 'Webpros' },
    { label: `${P}bot:organization:wp_umbrella`, displayName: 'Wp Umbrella' },
    { label: `${P}bot:organization:wpmudev`, displayName: 'Wpmudev' },
    { label: `${P}bot:organization:x`, displayName: 'X' },
    { label: `${P}bot:organization:xy_planning_network`, displayName: 'Xy Planning Network' },
    { label: `${P}bot:organization:yahoo`, displayName: 'Yahoo' },
    { label: `${P}bot:organization:yandex`, displayName: 'Yandex' },
    { label: `${P}bot:organization:yext`, displayName: 'Yext' },
    { label: `${P}bot:organization:zoho`, displayName: 'Zoho' },
    { label: `${P}bot:organization:zoovu`, displayName: 'Zoovu' },
    ],
  },
  {
    name: 'Bot Identity (custom)',
    labels: [],
    dynamicLabels: [
      { prefix: `${P}bot:vendor:`, displayName: 'Bot Vendor', placeholder: 'agentcore' },
      { prefix: `${P}bot:account:`, displayName: 'Bot Account (hash)', placeholder: 'abc123' },
    ],
  },
  {
    name: 'Web Bot Authentication',
    labels: [
      { label: `${P}bot:web_bot_auth:verified`, displayName: 'WBA Verified' },
      { label: `${P}bot:web_bot_auth:invalid`, displayName: 'WBA Invalid' },
      { label: `${P}bot:web_bot_auth:expired`, displayName: 'WBA Expired' },
      { label: `${P}bot:web_bot_auth:unknown_bot`, displayName: 'WBA Unknown Bot' },
    ],
  },
  {
    name: 'Signals',
    labels: [
      { label: `${P}signal:automated_browser`, displayName: 'Automated Browser' },
      { label: `${P}signal:known_bot_data_center`, displayName: 'Known Bot Data Center' },
      { label: `${P}signal:non_browser_user_agent`, displayName: 'Non-Browser User Agent' },
    ],
    dynamicLabels: [
      { prefix: `${P}signal:cloud_service_provider:`, displayName: 'Cloud Service Provider', placeholder: 'aws' },
    ],
  },
  {
    name: 'Targeted Signals',
    labels: [
      { label: `${P}targeted:signal:automated_browser`, displayName: 'Automated Browser (targeted)' },
      { label: `${P}targeted:signal:browser_automation_extension`, displayName: 'Browser Automation Extension' },
      { label: `${P}targeted:signal:browser_inconsistency`, displayName: 'Browser Inconsistency' },
    ],
  },
];

export const namespaceEntries: NamespaceEntry[] = [
  { namespace: `${P}bot:`, displayName: 'All Bot Control labels' },
  { namespace: `${P}bot:category:`, displayName: 'All Bot Categories' },
  { namespace: `${P}bot:name:`, displayName: 'All Bot Names' },
  { namespace: `${P}signal:`, displayName: 'All Signals' },
  { namespace: `${P}targeted:`, displayName: 'All Targeted' },
];

/** Flat list of all static labels for quick lookup */
export const allStaticLabels: LabelEntry[] = labelCategories.flatMap(c => c.labels);
