const P = 'awswaf:managed:aws:bot-control:';

export interface LabelEntry {
  label: string;
  displayName: string;
  description?: string;
}

export interface DynamicLabelEntry {
  prefix: string;
  displayName: string;
  placeholder: string;
  description?: string;
}

export interface LabelCategory {
  name: string;
  labels: LabelEntry[];
  dynamicLabels?: DynamicLabelEntry[];
}

export interface NamespaceEntry {
  namespace: string;
  displayName: string;
  description?: string;
}

export const labelCategories: LabelCategory[] = [
  {
    name: 'Bot Verification Status',
    labels: [
      { label: `${P}bot:verified`, displayName: 'Verified Bot', description: 'Bot that self-identifies and is independently verified' },
      { label: `${P}bot:unverified`, displayName: 'Unverified Bot', description: 'Bot that self-identifies but cannot be verified' },
      { label: `${P}bot:user_triggered:verified`, displayName: 'User-Triggered Bot (verified)', description: 'Verified bot invoked by end users' },
      { label: `${P}bot:developer_platform:verified`, displayName: 'Developer Platform Bot (verified)', description: 'Verified bot from dev platforms (e.g. Google Apps Script)' },
    ],
  },
  {
    name: 'Bot Category',
    labels: [
      { label: `${P}bot:category:ai`, displayName: 'AI Bot' },
      { label: `${P}bot:category:search_engine`, displayName: 'Search Engine' },
      { label: `${P}bot:category:content_fetcher`, displayName: 'Content Fetcher' },
      { label: `${P}bot:category:social_media`, displayName: 'Social Media' },
      { label: `${P}bot:category:advertising`, displayName: 'Advertising' },
      { label: `${P}bot:category:archiver`, displayName: 'Archiver' },
      { label: `${P}bot:category:seo`, displayName: 'SEO' },
      { label: `${P}bot:category:scraping_framework`, displayName: 'Scraping Framework' },
      { label: `${P}bot:category:http_library`, displayName: 'HTTP Library' },
      { label: `${P}bot:category:security`, displayName: 'Security' },
      { label: `${P}bot:category:monitoring`, displayName: 'Monitoring' },
      { label: `${P}bot:category:link_checker`, displayName: 'Link Checker' },
      { label: `${P}bot:category:email_client`, displayName: 'Email Client' },
      { label: `${P}bot:category:page_preview`, displayName: 'Page Preview' },
      { label: `${P}bot:category:webhooks`, displayName: 'Webhooks' },
      { label: `${P}bot:category:miscellaneous`, displayName: 'Miscellaneous' },
    ],
  },
  {
    name: 'Bot Names',
    labels: [
    { label: `${P}bot:name:2checkout`, displayName: '2Checkout *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:360monitoring`, displayName: '360Monitoring *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:360spider`, displayName: '360Spider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:aasa_bot`, displayName: 'Aasa Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:abcdatos`, displayName: 'Abcdatos *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:accessstatus`, displayName: 'Accessstatus *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:accoona`, displayName: 'Accoona *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:acme_spider`, displayName: 'Acme Spider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:acquia_optimize_monsido`, displayName: 'Acquia Optimize Monsido *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:activecomply_bot`, displayName: 'Activecomply Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:acunetix`, displayName: 'Acunetix *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:adagiobot`, displayName: 'Adagiobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:addthis`, displayName: 'Addthis *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:adidxbot`, displayName: 'Adidxbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:admantx`, displayName: 'Admantx *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:adstxtcrawler`, displayName: 'Adstxtcrawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:adyen`, displayName: 'Adyen *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:affiliate_crawler`, displayName: 'Affiliate Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:aftership_magento_2`, displayName: 'Aftership Magento 2 *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:agency_analytics_crawler`, displayName: 'Agency Analytics Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ahrefsbot`, displayName: 'Ahrefsbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ahrefssiteaudit`, displayName: 'Ahrefssiteaudit *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:akismet`, displayName: 'Akismet *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:alertsite`, displayName: 'Alertsite *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:alexabot`, displayName: 'Alexabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:algolia`, displayName: 'Algolia *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:allafrica_crawler`, displayName: 'Allafrica Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:almaden`, displayName: 'Almaden *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazon_adbot`, displayName: 'Amazon Adbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazon_contxtbot`, displayName: 'Amazon Contxtbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazon_kendra`, displayName: 'Amazon Kendra *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazon_product_discovery`, displayName: 'Amazon Product Discovery *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazonauditbot`, displayName: 'Amazonauditbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazonauditbot_mobile`, displayName: 'Amazonauditbot Mobile *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazonauditspider`, displayName: 'Amazonauditspider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:amazonbot`, displayName: 'AmazonBot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:android_programmatic_http_client`, displayName: 'Android Programmatic Http Client *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:anthropic`, displayName: 'Anthropic' },
    { label: `${P}bot:name:apache`, displayName: 'Apache *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:app_insights`, displayName: 'App Insights *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:appengine`, displayName: 'Appengine *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:applebot`, displayName: 'AppleBot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:applebot_extended`, displayName: 'AppleBot Extended *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:architext`, displayName: 'Architext *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:area_360`, displayName: 'Area 360 *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:artemis_web_reader`, displayName: 'Artemis Web Reader *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:asurioncrawler`, displayName: 'Asurioncrawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:atomz`, displayName: 'Atomz *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:attracta`, displayName: 'Attracta *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:audisto_crawler`, displayName: 'Audisto Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:authory`, displayName: 'Authory *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:automaton`, displayName: 'Automaton *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:automattic_tumblr`, displayName: 'Automattic Tumblr *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:avantgo`, displayName: 'Avantgo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:awario`, displayName: 'Awario *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:axios`, displayName: 'Axios *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:baidu`, displayName: 'Baidu *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:baiduspidermobile`, displayName: 'Baiduspidermobile *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:barkrowler`, displayName: 'Barkrowler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bazqux`, displayName: 'Bazqux *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bdfetch`, displayName: 'Bdfetch *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bedrockbot`, displayName: 'BedrockBot' },
    { label: `${P}bot:name:bestchange_bot`, displayName: 'Bestchange Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:better_uptime`, displayName: 'Better Uptime *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bibliotheque_nacional_de_france`, displayName: 'Bibliotheque Nacional De France *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:big_sur_ai`, displayName: 'Big Sur Ai *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bigupdatabot`, displayName: 'Bigupdatabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:binarycanary`, displayName: 'Binarycanary *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bingbot`, displayName: 'Bingbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bitbucket`, displayName: 'Bitbucket *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bitly`, displayName: 'Bitly *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:black_duck_fast_dynamic`, displayName: 'Black Duck Fast Dynamic *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:blexbot`, displayName: 'Blexbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bling_erp`, displayName: 'Bling Erp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:blinkx`, displayName: 'Blinkx *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:blockaid`, displayName: 'Blockaid *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:blogtrottr`, displayName: 'Blogtrottr *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:blogvault`, displayName: 'Blogvault *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bluesky_app`, displayName: 'Bluesky App *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:boardgameprices_bot`, displayName: 'Boardgameprices Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bomborabot`, displayName: 'Bomborabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:boneybadgerbot`, displayName: 'Boneybadgerbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:book_searcher`, displayName: 'Book Searcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:booko`, displayName: 'Booko *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bordermanager`, displayName: 'Bordermanager *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:botify`, displayName: 'Botify *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:brand_verity`, displayName: 'Brand Verity *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:brightedgebot`, displayName: 'Brightedgebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bugsnag`, displayName: 'Bugsnag *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bushbaby`, displayName: 'Bushbaby *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:buttondown_rss_feed_parser`, displayName: 'Buttondown Rss Feed Parser *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:bytespider`, displayName: 'ByteSpider' },
    { label: `${P}bot:name:caliperbot`, displayName: 'Caliperbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:camelhttpstream`, displayName: 'Camelhttpstream *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:capitalonebot`, displayName: 'Capitalonebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:catchpoint`, displayName: 'Catchpoint *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ccbot`, displayName: 'CCBot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:censys`, displayName: 'Censys' },
    { label: `${P}bot:name:cert_chief`, displayName: 'Cert Chief *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cf_digicert_dcv`, displayName: 'Cf Digicert Dcv *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:channable_importer`, displayName: 'Channable Importer *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:chargebee`, displayName: 'Chargebee *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:chatgpt`, displayName: 'ChatGPT *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:chatgpt_user`, displayName: 'ChatGPT User *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:checkbot`, displayName: 'Checkbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:checkly`, displayName: 'Checkly *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:checkmark_network`, displayName: 'Checkmark Network *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:chrome_lighthouse`, displayName: 'Chrome Lighthouse *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:claude_user`, displayName: 'Claude User *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:claude_web`, displayName: 'Claude Web *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:claudebot`, displayName: 'ClaudeBot' },
    { label: `${P}bot:name:clickagy`, displayName: 'Clickagy *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cliqzbot`, displayName: 'Cliqzbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cloudflare`, displayName: 'Cloudflare *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cloudtrellis`, displayName: 'Cloudtrellis *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cludobot`, displayName: 'Cludobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:coccoc`, displayName: 'Coccoc *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cognitiveseo`, displayName: 'Cognitiveseo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cohere`, displayName: 'Cohere' },
    { label: `${P}bot:name:coinbase`, displayName: 'Coinbase *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:comodo`, displayName: 'Comodo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:contentking`, displayName: 'Contentking *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:convermaxbot`, displayName: 'Convermaxbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cookie_hub`, displayName: 'Cookie Hub *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cookiebot`, displayName: 'Cookiebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cookiemaestro`, displayName: 'Cookiemaestro *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cotoyogi`, displayName: 'Cotoyogi *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:coveobot`, displayName: 'Coveobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cozi_icalendar`, displayName: 'Cozi Icalendar *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:crawler4j`, displayName: 'Crawler4J *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:crawlson`, displayName: 'Crawlson *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:crazy_egg_bot`, displayName: 'Crazy Egg Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:criteobot`, displayName: 'Criteobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:criticalcssbot`, displayName: 'Criticalcssbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cronjob`, displayName: 'Cronjob *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:curl`, displayName: 'Curl *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cxensebot`, displayName: 'Cxensebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:cydralspider`, displayName: 'Cydralspider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:datadog_synthetic_monitor`, displayName: 'Datadog Synthetic Monitor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:dataforseo_siteauditor`, displayName: 'Dataforseo Siteauditor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:dataforseobot`, displayName: 'Dataforseobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:datanyze`, displayName: 'Datanyze *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:dataprovider_com`, displayName: 'Dataprovider Com *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:datenbank`, displayName: 'Datenbank *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:daum`, displayName: 'Daum *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:deepcrawl`, displayName: 'Deepcrawl *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:detectify`, displayName: 'Detectify *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:devin`, displayName: 'Devin *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:diffbot`, displayName: 'Diffbot' },
    { label: `${P}bot:name:digext`, displayName: 'Digext *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:digicert_dcv`, displayName: 'Digicert Dcv *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:discordbot`, displayName: 'Discordbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:docomo`, displayName: 'Docomo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:dotbot`, displayName: 'Dotbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:dotcom_monitor`, displayName: 'Dotcom Monitor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:doubleverify`, displayName: 'Doubleverify *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:drlinkcheck`, displayName: 'Drlinkcheck *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:drupal`, displayName: 'Drupal *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:duckassistbot`, displayName: 'DuckAssistBot' },
    { label: `${P}bot:name:duckduckbot`, displayName: 'Duckduckbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:duckduckgo_favicons_bot`, displayName: 'Duckduckgo Favicons Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:easybill_import_manager`, displayName: 'Easybill Import Manager *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:easycron`, displayName: 'Easycron *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:easydns`, displayName: 'Easydns *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:echoboxbot`, displayName: 'Echoboxbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:elmahio_uptimebot`, displayName: 'Elmahio Uptimebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:email_marketing_high_priority`, displayName: 'Email Marketing High Priority *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:email_marketing_low_priority`, displayName: 'Email Marketing Low Priority *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:embedly`, displayName: 'Embedly *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:emcspider`, displayName: 'Emcspider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:emoneybot`, displayName: 'Emoneybot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:epivoz_crawler`, displayName: 'Epivoz Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:erepublik_tools`, displayName: 'Erepublik Tools *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:etaospider`, displayName: 'Etaospider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:evensi`, displayName: 'Evensi' },
    { label: `${P}bot:name:eventmachine`, displayName: 'Eventmachine *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:evo_uptime_bot`, displayName: 'Evo Uptime Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:exabot_thumbnails`, displayName: 'Exabot Thumbnails *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:exodus_movement`, displayName: 'Exodus Movement *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ezoicbot`, displayName: 'Ezoicbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ezooms`, displayName: 'Ezooms *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:facebook`, displayName: 'Facebook *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:facebook_bot`, displayName: 'Facebook Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:facebot`, displayName: 'Facebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:factset_spyderbot`, displayName: 'Factset Spyderbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fake_ie60_java`, displayName: 'Fake Ie60 Java *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fastenterprise`, displayName: 'Fastenterprise *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fasthttp`, displayName: 'FastHTTP' },
    { label: `${P}bot:name:fastmail_bot`, displayName: 'Fastmail Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fastwebcrawler`, displayName: 'Fastwebcrawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fdl_stats_bot`, displayName: 'Fdl Stats Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fedreporter_bot_for_ffiec`, displayName: 'Fedreporter Bot For Ffiec *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feedbin`, displayName: 'Feedbin *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feedburner`, displayName: 'Feedburner *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feeder`, displayName: 'Feeder *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feedfinder`, displayName: 'Feedfinder *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feedly`, displayName: 'Feedly *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feedspot`, displayName: 'Feedspot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:feedwind`, displayName: 'Feedwind *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fetch`, displayName: 'Fetch *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:findlinks`, displayName: 'Findlinks *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:flipboard`, displayName: 'Flipboard *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:foregenix_threatview_webscan`, displayName: 'Foregenix Threatview Webscan *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:freespoke`, displayName: 'Freespoke *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:freshpingbot`, displayName: 'Freshpingbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:fullstorybot`, displayName: 'Fullstorybot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:funnelback`, displayName: 'Funnelback *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:garlik`, displayName: 'Garlik *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gemini_deep_research`, displayName: 'Gemini Deep Research *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:generic_crawler`, displayName: 'Generic Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:generic_search_bot`, displayName: 'Generic Search Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:genieo`, displayName: 'Genieo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:getintent`, displayName: 'Getintent *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ghost_inspector`, displayName: 'Ghost Inspector *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gigabot`, displayName: 'Gigabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:go_http`, displayName: 'Go Http *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gomez`, displayName: 'Gomez *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_adsbot`, displayName: 'Google Adsbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_adsense`, displayName: 'Google Adsense *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_adwords_express`, displayName: 'Google Adwords Express *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_adwords_instant`, displayName: 'Google Adwords Instant *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_apis`, displayName: 'Google Apis *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_app_engine`, displayName: 'Google App Engine *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_apps_script`, displayName: 'Google Apps Script *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_association_service`, displayName: 'Google Association Service *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_cloud_vertex_bot`, displayName: 'Google Cloud Vertex Bot' },
    { label: `${P}bot:name:google_common_crawler`, displayName: 'Google Common Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_favicon`, displayName: 'Google Favicon *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_feedfetcher`, displayName: 'Google Feedfetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_http_java_client`, displayName: 'Google Http Java Client *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_imageproxy`, displayName: 'Google Imageproxy *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_inspection_tool`, displayName: 'Google Inspection Tool *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_lighthouse`, displayName: 'Google Lighthouse *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_mediapartners`, displayName: 'Google Mediapartners *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_other`, displayName: 'Google Other *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_pagerenderer`, displayName: 'Google Pagerenderer *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_publisher_center`, displayName: 'Google Publisher Center *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_read_aloud`, displayName: 'Google Read Aloud *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_safety`, displayName: 'Google Safety *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_scholar`, displayName: 'Google Scholar *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_site_verification`, displayName: 'Google Site Verification *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_special_case_crawler`, displayName: 'Google Special Case Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_storebot`, displayName: 'Google Storebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_trust_services`, displayName: 'Google Trust Services *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_user_triggered_fetcher`, displayName: 'Google User Triggered Fetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:google_web_preview`, displayName: 'Google Web Preview *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebot`, displayName: 'Googlebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebot_ezweb_mobile`, displayName: 'Googlebot Ezweb Mobile *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebotadwordsmobile`, displayName: 'Googlebotadwordsmobile *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebotimage`, displayName: 'Googlebotimage *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebotimages`, displayName: 'Googlebotimages *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebotmobile`, displayName: 'Googlebotmobile *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebotsimple`, displayName: 'Googlebotsimple *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlebotvideos`, displayName: 'Googlebotvideos *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googledata`, displayName: 'Googledata *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlesearchappliance`, displayName: 'Googlesearchappliance *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googleweblight`, displayName: 'Googleweblight *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:googlewebmastertools`, displayName: 'Googlewebmastertools *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gopay`, displayName: 'Gopay *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gptbot`, displayName: 'GPTBot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:grafana_labs`, displayName: 'Grafana Labs *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:grapeshot`, displayName: 'Grapeshot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:groovinads`, displayName: 'Groovinads *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:grub`, displayName: 'Grub *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gsitecrawler`, displayName: 'Gsitecrawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gtmetrix`, displayName: 'Gtmetrix *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:guestpostsbot`, displayName: 'Guestpostsbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:gulperbot`, displayName: 'Gulperbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:guzzle`, displayName: 'Guzzle *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:harvester`, displayName: 'Harvester *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hatena`, displayName: 'Hatena *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hellowork_bot`, displayName: 'Hellowork Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:helpfeel_notabot`, displayName: 'Helpfeel Notabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:heritrix`, displayName: 'Heritrix *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hetrixtools`, displayName: 'Hetrixtools *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hifibot`, displayName: 'Hifibot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hiongun`, displayName: 'Hiongun *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hosttracker`, displayName: 'Hosttracker *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hstspreload_bot`, displayName: 'Hstspreload Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:httplite`, displayName: 'Httplite *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:httprequester`, displayName: 'Httprequester *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hubspot`, displayName: 'Hubspot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hubspot_feed_fetcher`, displayName: 'Hubspot Feed Fetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hubspot_page_fetcher`, displayName: 'Hubspot Page Fetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:huckabot`, displayName: 'Huckabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:hypemachine`, displayName: 'Hypemachine *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ias_crawler`, displayName: 'Ias Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ichiro`, displayName: 'Ichiro *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:iframely`, displayName: 'Iframely *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ifttt_rss_feed_service`, displayName: 'Ifttt Rss Feed Service *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:imagesift`, displayName: 'ImageSift' },
    { label: `${P}bot:name:imessage_preview`, displayName: 'iMessage Preview' },
    { label: `${P}bot:name:inktomi_slurp`, displayName: 'Inktomi Slurp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:innguma_fetcher`, displayName: 'Innguma Fetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:innologica`, displayName: 'Innologica *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:instapaper`, displayName: 'Instapaper *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:integromatbot`, displayName: 'Integromatbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:internet_archive`, displayName: 'Internet Archive *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ipworks`, displayName: 'Ipworks *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:isdownbot`, displayName: 'Isdownbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:isecbot`, displayName: 'Isecbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:jagged_pixel_uptime`, displayName: 'Jagged Pixel Uptime *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:jakarta`, displayName: 'Jakarta *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:java`, displayName: 'Java *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:javahttpclient`, displayName: 'Javahttpclient *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:jersey`, displayName: 'Jersey *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:jetpack`, displayName: 'Jetpack *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:jobswithgptcom_bot`, displayName: 'Jobswithgptcom Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:jumio`, displayName: 'Jumio *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:kagi`, displayName: 'Kagi *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:kargobot_artemis`, displayName: 'Kargobot Artemis *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:kinsta_bot`, displayName: 'Kinsta Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:klaviyo`, displayName: 'Klaviyo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:legalmonster`, displayName: 'Legalmonster *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:letsencrypt`, displayName: 'Letsencrypt *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:level_9_search_bot`, displayName: 'Level 9 Search Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:libhttp`, displayName: 'Libhttp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:libperl`, displayName: 'Libperl *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:library_of_congress_web_archiving`, displayName: 'Library Of Congress Web Archiving *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linespider`, displayName: 'Linespider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linguee`, displayName: 'Linguee *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linkchecker`, displayName: 'Linkchecker *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linkdex`, displayName: 'Linkdex *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linkedin`, displayName: 'Linkedin *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linklint`, displayName: 'Linklint *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linkscan`, displayName: 'Linkscan *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linksindexerbot`, displayName: 'Linksindexerbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linksmanager`, displayName: 'Linksmanager *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linktiger`, displayName: 'Linktiger *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linkup`, displayName: 'Linkup *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:linkwalker`, displayName: 'Linkwalker *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:livedoor`, displayName: 'Livedoor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:livedoor_feedfetcher`, displayName: 'Livedoor Feedfetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:livelapbot`, displayName: 'Livelapbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:logicmonitor`, displayName: 'Logicmonitor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:loomlybot`, displayName: 'Loomlybot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:lydia`, displayName: 'Lydia *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:macrobondbot`, displayName: 'Macrobondbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:magibot`, displayName: 'Magibot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:magnetmebot`, displayName: 'Magnetmebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:magpie`, displayName: 'Magpie *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mailru`, displayName: 'Mailru *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mainwp`, displayName: 'Mainwp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:make_platform`, displayName: 'Make Platform *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:managewp`, displayName: 'Managewp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:marfeel`, displayName: 'Marfeel *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:marginaliabot`, displayName: 'Marginaliabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:marketgoo`, displayName: 'Marketgoo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mars_finder`, displayName: 'Mars Finder *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mauibot`, displayName: 'Mauibot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:maverick`, displayName: 'Maverick *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mavifinds_bot`, displayName: 'Mavifinds Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:media_monitoring_bot`, displayName: 'Media Monitoring Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:medialogiabot`, displayName: 'Medialogiabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mediatoolkitbot`, displayName: 'Mediatoolkitbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mediavine_metadata_parser`, displayName: 'Mediavine Metadata Parser *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:megaindex`, displayName: 'Megaindex *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:melonmesabot`, displayName: 'Melonmesabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:meta-externalads`, displayName: 'Meta External Ads' },
    { label: `${P}bot:name:meta-externalagent`, displayName: 'Meta External Agent' },
    { label: `${P}bot:name:meta-externalfetcher`, displayName: 'Meta External Fetcher' },
    { label: `${P}bot:name:meta-webindexer`, displayName: 'Meta Web Indexer' },
    { label: `${P}bot:name:metaexternalagent`, displayName: 'MetaExternalAgent' },
    { label: `${P}bot:name:metauri`, displayName: 'Metauri *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:metorik`, displayName: 'Metorik *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mgidbot`, displayName: 'Mgidbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:microsoft_preview`, displayName: 'Microsoft Preview *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:miniflux`, displayName: 'Miniflux *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mirrorwebcrawler`, displayName: 'Mirrorwebcrawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:missinglettrbot`, displayName: 'Missinglettrbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mistralai_user`, displayName: 'MistralAI User *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mixi_check`, displayName: 'Mixi Check *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mixrankbot`, displayName: 'Mixrankbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mj12bot`, displayName: 'Mj12Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mnogosearch`, displayName: 'Mnogosearch *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:moatbot`, displayName: 'Moatbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:modular_ds`, displayName: 'Modular Ds *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mojeek`, displayName: 'Mojeek *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:molliebot`, displayName: 'Molliebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:momspider`, displayName: 'Momspider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mon_spark`, displayName: 'Mon Spark *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:monitis`, displayName: 'Monitis *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:monitorss`, displayName: 'Monitorss *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:montasticmonitor`, displayName: 'Montasticmonitor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:moodlebot`, displayName: 'Moodlebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:motominerbot`, displayName: 'Motominerbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mrgbot`, displayName: 'Mrgbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:msnbot`, displayName: 'Msnbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:mushilabs_clearscopebot`, displayName: 'Mushilabs Clearscopebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:naver`, displayName: 'Naver' },
    { label: `${P}bot:name:naver_ads`, displayName: 'Naver Ads' },
    { label: `${P}bot:name:naver_preview`, displayName: 'Naver Preview' },
    { label: `${P}bot:name:neevabot`, displayName: 'Neevabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:netcraft`, displayName: 'Netcraft *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:netumo`, displayName: 'Netumo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:netvibes`, displayName: 'Netvibes *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:netvigie`, displayName: 'Netvigie *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:never_converting_netscape`, displayName: 'Never Converting Netscape *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:new_york_times_newsgathering`, displayName: 'New York Times Newsgathering *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:newrelic`, displayName: 'Newrelic *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:newrelic_synthetic_monitor`, displayName: 'Newrelic Synthetic Monitor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:news_blur`, displayName: 'News Blur *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:newsnow`, displayName: 'Newsnow *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:newspaper`, displayName: 'Newspaper *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nimbostratus`, displayName: 'Nimbostratus *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nitro`, displayName: 'Nitro *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nixstats`, displayName: 'Nixstats *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:node_fetch`, displayName: 'Node Fetch *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nodeping`, displayName: 'Nodeping *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:noibu`, displayName: 'Noibu *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nokia_jumpbot_mobile`, displayName: 'Nokia Jumpbot Mobile *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:noorobot`, displayName: 'Noorobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nooshub`, displayName: 'Nooshub *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nova_act`, displayName: 'Nova Act' },
    { label: `${P}bot:name:ntt_docomo_foma_crawler`, displayName: 'Ntt Docomo Foma Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ntt_docomo_mova_crawler`, displayName: 'Ntt Docomo Mova Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ntt_docomo_yahoo_au_crawler`, displayName: 'Ntt Docomo Yahoo Au Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ntt_docomo_yahoo_docomo_crawler`, displayName: 'Ntt Docomo Yahoo Docomo Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ntt_docomo_yahoo_softbank_crawler`, displayName: 'Ntt Docomo Yahoo Softbank Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:nytimes`, displayName: 'NYTimes' },
    { label: `${P}bot:name:objectssearch`, displayName: 'Objectssearch *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ohdear`, displayName: 'Ohdear *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:okhttp`, displayName: 'Okhttp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:omgili`, displayName: 'Omgili' },
    { label: `${P}bot:name:omnisend`, displayName: 'Omnisend *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:oncrawl`, displayName: 'Oncrawl *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:onetrust_cmp_scanner`, displayName: 'Onetrust Cmp Scanner *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:online_webceo_bot`, displayName: 'Online Webceo Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:onlineornot`, displayName: 'Onlineornot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ontospider`, displayName: 'Ontospider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:opengraphbot`, displayName: 'Opengraphbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:openrss`, displayName: 'Openrss *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:oracleultrasearch`, displayName: 'Oracleultrasearch *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:orlo_link_preview`, displayName: 'Orlo Link Preview *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:outbrain`, displayName: 'Outbrain *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:outlook`, displayName: 'Outlook *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:outsell_url_validator`, displayName: 'Outsell Url Validator *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:overcast`, displayName: 'Overcast *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ozon_web_grabber`, displayName: 'Ozon Web Grabber *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pandalytics`, displayName: 'Pandalytics *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:panopta`, displayName: 'Panopta *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:paperlibot`, displayName: 'Paperlibot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:parsely`, displayName: 'Parsely *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:paypal`, displayName: 'Paypal *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pci_qualys`, displayName: 'Pci Qualys *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pdns_monitor`, displayName: 'Pdns Monitor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pear_php`, displayName: 'Pear Php *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:perplexity-user`, displayName: 'Perplexity User' },
    { label: `${P}bot:name:perplexitybot`, displayName: 'PerplexityBot' },
    { label: `${P}bot:name:petalbot`, displayName: 'Petalbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:phpcrawl`, displayName: 'Phpcrawl *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pingability`, displayName: 'Pingability *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pingdom`, displayName: 'Pingdom *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pingping`, displayName: 'Pingping *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pinterest`, displayName: 'Pinterest *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pocket`, displayName: 'Pocket *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pocketcasts_feed_parser`, displayName: 'Pocketcasts Feed Parser *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:poe`, displayName: 'Poe *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:potions`, displayName: 'Potions *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:prerender`, displayName: 'Prerender *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:press_engine_bot`, displayName: 'Press Engine Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:printfriendly`, displayName: 'Printfriendly *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pro_sitemaps`, displayName: 'Pro Sitemaps *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:proctorio`, displayName: 'Proctorio *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:project_honeypot`, displayName: 'Project Honeypot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:project_shield_urlcheck`, displayName: 'Project Shield Urlcheck *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:protopage`, displayName: 'Protopage *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:proximic`, displayName: 'Proximic *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:prtg`, displayName: 'Prtg *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:psbot`, displayName: 'Psbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pulsetic`, displayName: 'Pulsetic *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:pwabuilder`, displayName: 'Pwabuilder *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:python`, displayName: 'Python *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:python_requests`, displayName: 'Python Requests *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:qualifiedbot`, displayName: 'Qualifiedbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:qualys`, displayName: 'Qualys *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:quantcastbot`, displayName: 'Quantcastbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:queryseekerspider`, displayName: 'Queryseekerspider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:quorabot`, displayName: 'Quorabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:qwantify`, displayName: 'Qwantify *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:rackspace`, displayName: 'Rackspace *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:rakutenusabot_image`, displayName: 'Rakutenusabot Image *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:readable`, displayName: 'Readable *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:redditbot`, displayName: 'Redditbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:reelevant`, displayName: 'Reelevant *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:retool`, displayName: 'Retool *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:retrolistecom`, displayName: 'Retrolistecom *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:revvim`, displayName: 'Revvim *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:reward_gateway`, displayName: 'Reward Gateway *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:riddler`, displayName: 'Riddler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:rigor`, displayName: 'Rigor *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:rogerbot`, displayName: 'Rogerbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:route53_health_check`, displayName: 'Route53 Health Check *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:rss2tg_bot`, displayName: 'Rss2Tg Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:rssapi`, displayName: 'Rssapi *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:ruby`, displayName: 'Ruby *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sae`, displayName: 'Sae *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:salesforce`, displayName: 'Salesforce *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:salesviewer`, displayName: 'Salesviewer *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:scanalert`, displayName: 'Scanalert *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:scanpower`, displayName: 'Scanpower *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:schmozilla`, displayName: 'Schmozilla *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:scour_rss_bot`, displayName: 'Scour Rss Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:scrapy`, displayName: 'Scrapy *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:se_ranking_bot`, displayName: 'Se Ranking Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:searchatlas_bot`, displayName: 'Searchatlas Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:searchbot`, displayName: 'SearchBot' },
    { label: `${P}bot:name:securityheaders`, displayName: 'Securityheaders *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:seekportbot`, displayName: 'Seekportbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:semanticscholarbot`, displayName: 'Semanticscholarbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:semrush_siteauditbot`, displayName: 'Semrush Siteauditbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:semrushbot`, displayName: 'Semrushbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sendgrid`, displayName: 'Sendgrid *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sentibot`, displayName: 'Sentibot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sentry`, displayName: 'Sentry *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sentry_uptime_monitoring`, displayName: 'Sentry Uptime Monitoring *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:seo4ajax`, displayName: 'Seo4Ajax *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:seo_audit_check_bot`, displayName: 'Seo Audit Check Bot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:seobilitybot`, displayName: 'Seobilitybot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sequelwpbpt`, displayName: 'Sequelwpbpt *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:serpstatbot`, displayName: 'Serpstatbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:serverdensity`, displayName: 'Serverdensity *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:serverhunter`, displayName: 'Serverhunter *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:seznam`, displayName: 'Seznam *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:shopify_captain_hook`, displayName: 'Shopify Captain Hook *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:shortwave_image_fetcher`, displayName: 'Shortwave Image Fetcher *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:siege`, displayName: 'Siege *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:silktidebot`, displayName: 'Silktidebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:similar_tech`, displayName: 'Similar Tech *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sistrixcrawler`, displayName: 'Sistrixcrawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:site24x7`, displayName: 'Site24X7 *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:site_improve`, displayName: 'Site Improve *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:site_search_360`, displayName: 'Site Search 360 *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sitecheck_sitecrawl`, displayName: 'Sitecheck Sitecrawl *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:siteimprove_linkcheck`, displayName: 'Siteimprove Linkcheck *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sitelock`, displayName: 'Sitelock *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:siteuptime`, displayName: 'Siteuptime *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:skroutzbot`, displayName: 'Skroutzbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:skroutzimagebot`, displayName: 'Skroutzimagebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:skypeuripreview`, displayName: 'Skypeuripreview *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:slack_images`, displayName: 'Slack Images *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:slackbot`, displayName: 'Slackbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:slackbotlinkexpanding`, displayName: 'Slackbotlinkexpanding *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:slickstream`, displayName: 'Slickstream *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:smartologybot`, displayName: 'Smartologybot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:smtnetpmbot`, displayName: 'Smtnetpmbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:snapchat`, displayName: 'Snapchat' },
    { label: `${P}bot:name:snipcart`, displayName: 'Snipcart *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:snoopy`, displayName: 'Snoopy *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sogou`, displayName: 'Sogou *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:solarwinds_observability`, displayName: 'Solarwinds Observability *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sora_caisse_pos`, displayName: 'Sora Caisse Pos *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sosospider`, displayName: 'Sosospider *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:spark_shipping`, displayName: 'Spark Shipping *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sparkpost`, displayName: 'Sparkpost *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:spectate`, displayName: 'Spectate *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:splunk_attack_analyzer`, displayName: 'Splunk Attack Analyzer *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:splunk_synthetics`, displayName: 'Splunk Synthetics *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:stape_scanner`, displayName: 'Stape Scanner *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:statabot`, displayName: 'Statabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:statistikaustria`, displayName: 'Statistikaustria *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:statsdronebot`, displayName: 'Statsdronebot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:statuscake`, displayName: 'Statuscake *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:steam_chat`, displayName: 'Steam Chat *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:steeler`, displayName: 'Steeler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:strata2crawler`, displayName: 'Strata2Crawler *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:stripe`, displayName: 'Stripe *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:study_partner`, displayName: 'Study Partner *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:sumologic`, displayName: 'Sumologic *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:superfeedr`, displayName: 'Superfeedr *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:taboolabot`, displayName: 'Taboolabot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:telegram`, displayName: 'Telegram *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:tiktok`, displayName: 'TikTok' },
    { label: `${P}bot:name:timpibot`, displayName: 'TimpiBot' },
    { label: `${P}bot:name:tin_eye`, displayName: 'Tin Eye *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:tiny_rss`, displayName: 'Tiny Rss *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:trendictionbot`, displayName: 'Trendictionbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:twitter`, displayName: 'Twitter *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:uptimerobot`, displayName: 'Uptimerobot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:w3c`, displayName: 'W3C *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:w3c_validation_services`, displayName: 'W3C Validation Services *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:wappalyzer`, displayName: 'Wappalyzer *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:web_copier`, displayName: 'Web Copier *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:wget`, displayName: 'Wget *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:whatsapp`, displayName: 'Whatsapp *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:wordpress_scanner`, displayName: 'Wordpress Scanner *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:yacy`, displayName: 'Yacy *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:yahoo`, displayName: 'Yahoo *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:yahoo_mail`, displayName: 'Yahoo Mail *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:yandexbot`, displayName: 'Yandexbot *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:yanga`, displayName: 'Yanga *', description: '* Name not forwarded to origin as header' },
    { label: `${P}bot:name:yisouspider`, displayName: 'YisouSpider' },
    { label: `${P}bot:name:zyborg`, displayName: 'Zyborg *', description: '* Name not forwarded to origin as header' },
    ],
  },
  {
    name: 'Bot Organizations',
    labels: [
    { label: `${P}bot:organization:acquia`, displayName: 'Acquia' },
    { label: `${P}bot:organization:adyen`, displayName: 'Adyen' },
    { label: `${P}bot:organization:agencyanalytics`, displayName: 'Agencyanalytics' },
    { label: `${P}bot:organization:ahrefs`, displayName: 'Ahrefs' },
    { label: `${P}bot:organization:airo`, displayName: 'Airo' },
    { label: `${P}bot:organization:algolia`, displayName: 'Algolia' },
    { label: `${P}bot:organization:amazon`, displayName: 'Amazon' },
    { label: `${P}bot:organization:anthropic`, displayName: 'Anthropic' },
    { label: `${P}bot:organization:apple`, displayName: 'Apple' },
    { label: `${P}bot:organization:atlassian`, displayName: 'Atlassian' },
    { label: `${P}bot:organization:audisto`, displayName: 'Audisto' },
    { label: `${P}bot:organization:automattic`, displayName: 'Automattic' },
    { label: `${P}bot:organization:baidu`, displayName: 'Baidu' },
    { label: `${P}bot:organization:betterstack`, displayName: 'Betterstack' },
    { label: `${P}bot:organization:blogvault`, displayName: 'Blogvault' },
    { label: `${P}bot:organization:brandwatch`, displayName: 'Brandwatch' },
    { label: `${P}bot:organization:buttondown`, displayName: 'Buttondown' },
    { label: `${P}bot:organization:bytedance`, displayName: 'ByteDance' },
    { label: `${P}bot:organization:capjamesg`, displayName: 'Capjamesg' },
    { label: `${P}bot:organization:censys`, displayName: 'Censys' },
    { label: `${P}bot:organization:cludo`, displayName: 'Cludo' },
    { label: `${P}bot:organization:cognition`, displayName: 'Cognition' },
    { label: `${P}bot:organization:common_crawl`, displayName: 'Common Crawl' },
    { label: `${P}bot:organization:comscore`, displayName: 'Comscore' },
    { label: `${P}bot:organization:cookiehub`, displayName: 'Cookiehub' },
    { label: `${P}bot:organization:criteo`, displayName: 'Criteo' },
    { label: `${P}bot:organization:datadog`, displayName: 'Datadog' },
    { label: `${P}bot:organization:dataforseo`, displayName: 'Dataforseo' },
    { label: `${P}bot:organization:designmodo`, displayName: 'Designmodo' },
    { label: `${P}bot:organization:digicert`, displayName: 'Digicert' },
    { label: `${P}bot:organization:duckduckgo`, displayName: 'DuckDuckGo' },
    { label: `${P}bot:organization:easycron`, displayName: 'Easycron' },
    { label: `${P}bot:organization:elmahio`, displayName: 'Elmahio' },
    { label: `${P}bot:organization:facebook`, displayName: 'Facebook' },
    { label: `${P}bot:organization:feedbin`, displayName: 'Feedbin' },
    { label: `${P}bot:organization:flipboard`, displayName: 'Flipboard' },
    { label: `${P}bot:organization:foxhound_systems`, displayName: 'Foxhound Systems' },
    { label: `${P}bot:organization:godaddy`, displayName: 'Godaddy' },
    { label: `${P}bot:organization:google`, displayName: 'Google' },
    { label: `${P}bot:organization:hetrixtools`, displayName: 'Hetrixtools' },
    { label: `${P}bot:organization:host-tracker`, displayName: 'Host Tracker' },
    { label: `${P}bot:organization:huawei`, displayName: 'Huawei' },
    { label: `${P}bot:organization:hubspot`, displayName: 'HubSpot' },
    { label: `${P}bot:organization:huckabuy`, displayName: 'Huckabuy' },
    { label: `${P}bot:organization:immutable`, displayName: 'Immutable' },
    { label: `${P}bot:organization:incsub`, displayName: 'Incsub' },
    { label: `${P}bot:organization:isdown`, displayName: 'Isdown' },
    { label: `${P}bot:organization:jumio`, displayName: 'Jumio' },
    { label: `${P}bot:organization:kagiinc`, displayName: 'Kagiinc' },
    { label: `${P}bot:organization:kalpraj_solutions`, displayName: 'Kalpraj Solutions' },
    { label: `${P}bot:organization:line`, displayName: 'Line' },
    { label: `${P}bot:organization:lumar`, displayName: 'Lumar' },
    { label: `${P}bot:organization:magnetme`, displayName: 'Magnetme' },
    { label: `${P}bot:organization:majestic`, displayName: 'Majestic' },
    { label: `${P}bot:organization:make`, displayName: 'Make' },
    { label: `${P}bot:organization:marfeel`, displayName: 'Marfeel' },
    { label: `${P}bot:organization:marginaliasearch`, displayName: 'Marginaliasearch' },
    { label: `${P}bot:organization:medialogia`, displayName: 'Medialogia' },
    { label: `${P}bot:organization:mediamonitoringbot`, displayName: 'Mediamonitoringbot' },
    { label: `${P}bot:organization:microsoft`, displayName: 'Microsoft' },
    { label: `${P}bot:organization:monspark`, displayName: 'Monspark' },
    { label: `${P}bot:organization:motominer`, displayName: 'Motominer' },
    { label: `${P}bot:organization:mozilla`, displayName: 'Mozilla' },
    { label: `${P}bot:organization:mushi_labs`, displayName: 'Mushi Labs' },
    { label: `${P}bot:organization:naver`, displayName: 'Naver' },
    { label: `${P}bot:organization:new_relic`, displayName: 'New Relic' },
    { label: `${P}bot:organization:newsblur`, displayName: 'Newsblur' },
    { label: `${P}bot:organization:nitropack`, displayName: 'Nitropack' },
    { label: `${P}bot:organization:nodeping`, displayName: 'Nodeping' },
    { label: `${P}bot:organization:nytimes`, displayName: 'Nytimes' },
    { label: `${P}bot:organization:omnisend`, displayName: 'Omnisend' },
    { label: `${P}bot:organization:oncrawl`, displayName: 'Oncrawl' },
    { label: `${P}bot:organization:openai`, displayName: 'OpenAI' },
    { label: `${P}bot:organization:oracle`, displayName: 'Oracle' },
    { label: `${P}bot:organization:paypal`, displayName: 'PayPal' },
    { label: `${P}bot:organization:perplexity`, displayName: 'Perplexity' },
    { label: `${P}bot:organization:pinterest`, displayName: 'Pinterest' },
    { label: `${P}bot:organization:pressengine`, displayName: 'Pressengine' },
    { label: `${P}bot:organization:pro_sitemaps`, displayName: 'Pro Sitemaps' },
    { label: `${P}bot:organization:probely`, displayName: 'Probely' },
    { label: `${P}bot:organization:qualified`, displayName: 'Qualified' },
    { label: `${P}bot:organization:qualys`, displayName: 'Qualys' },
    { label: `${P}bot:organization:quantcast`, displayName: 'Quantcast' },
    { label: `${P}bot:organization:qwant`, displayName: 'Qwant' },
    { label: `${P}bot:organization:raptive`, displayName: 'Raptive' },
    { label: `${P}bot:organization:realify`, displayName: 'Realify' },
    { label: `${P}bot:organization:retool`, displayName: 'Retool' },
    { label: `${P}bot:organization:rois`, displayName: 'Rois' },
    { label: `${P}bot:organization:saasgroup`, displayName: 'Saasgroup' },
    { label: `${P}bot:organization:se_ranking`, displayName: 'Se Ranking' },
    { label: `${P}bot:organization:seekport`, displayName: 'Seekport' },
    { label: `${P}bot:organization:semrush`, displayName: 'Semrush' },
    { label: `${P}bot:organization:sentry`, displayName: 'Sentry' },
    { label: `${P}bot:organization:serverhunter`, displayName: 'Serverhunter' },
    { label: `${P}bot:organization:seznam`, displayName: 'Seznam' },
    { label: `${P}bot:organization:siteimprove`, displayName: 'Siteimprove' },
    { label: `${P}bot:organization:siteuptime`, displayName: 'Siteuptime' },
    { label: `${P}bot:organization:skroutz`, displayName: 'Skroutz' },
    { label: `${P}bot:organization:slack`, displayName: 'Slack' },
    { label: `${P}bot:organization:smartbear`, displayName: 'Smartbear' },
    { label: `${P}bot:organization:snap`, displayName: 'Snap' },
    { label: `${P}bot:organization:sogou`, displayName: 'Sogou' },
    { label: `${P}bot:organization:solarwinds`, displayName: 'Solarwinds' },
    { label: `${P}bot:organization:sspworks`, displayName: 'Sspworks' },
    { label: `${P}bot:organization:stape`, displayName: 'Stape' },
    { label: `${P}bot:organization:stripe`, displayName: 'Stripe' },
    { label: `${P}bot:organization:sureswiftcapital`, displayName: 'Sureswiftcapital' },
    { label: `${P}bot:organization:svix`, displayName: 'Svix' },
    { label: `${P}bot:organization:synopsys`, displayName: 'Synopsys' },
    { label: `${P}bot:organization:taboola`, displayName: 'Taboola' },
    { label: `${P}bot:organization:telegram`, displayName: 'Telegram' },
    { label: `${P}bot:organization:the_trade_desk`, displayName: 'The Trade Desk' },
    { label: `${P}bot:organization:updown`, displayName: 'Updown' },
    { label: `${P}bot:organization:uptimia`, displayName: 'Uptimia' },
    { label: `${P}bot:organization:uptrends`, displayName: 'Uptrends' },
    { label: `${P}bot:organization:w3c`, displayName: 'W3C' },
    { label: `${P}bot:organization:ward`, displayName: 'Ward' },
    { label: `${P}bot:organization:watchful`, displayName: 'Watchful' },
    { label: `${P}bot:organization:webceo`, displayName: 'Webceo' },
    { label: `${P}bot:organization:webpros`, displayName: 'Webpros' },
    { label: `${P}bot:organization:wp_umbrella`, displayName: 'Wp Umbrella' },
    { label: `${P}bot:organization:wpmudev`, displayName: 'Wpmudev' },
    { label: `${P}bot:organization:x`, displayName: 'X' },
    { label: `${P}bot:organization:xy_planning_network`, displayName: 'Xy Planning Network' },
    { label: `${P}bot:organization:yahoo`, displayName: 'Yahoo' },
    { label: `${P}bot:organization:yandex`, displayName: 'Yandex' },
    { label: `${P}bot:organization:yext`, displayName: 'Yext' },
    { label: `${P}bot:organization:zoho`, displayName: 'Zoho' },
    { label: `${P}bot:organization:zoovu`, displayName: 'Zoovu' },
    ],
  },
  {
    name: 'Bot Identity (custom)',
    labels: [],
    dynamicLabels: [
      { prefix: `${P}bot:vendor:`, displayName: 'Bot Vendor', placeholder: 'agentcore' },
      { prefix: `${P}bot:account:`, displayName: 'Bot Account (hash)', placeholder: 'abc123' },
    ],
  },
  {
    name: 'Web Bot Authentication',
    labels: [
      { label: `${P}bot:web_bot_auth:verified`, displayName: 'WBA Verified' },
      { label: `${P}bot:web_bot_auth:invalid`, displayName: 'WBA Invalid' },
      { label: `${P}bot:web_bot_auth:expired`, displayName: 'WBA Expired' },
      { label: `${P}bot:web_bot_auth:unknown_bot`, displayName: 'WBA Unknown Bot' },
    ],
  },
  {
    name: 'Signals',
    labels: [
      { label: `${P}signal:automated_browser`, displayName: 'Automated Browser' },
      { label: `${P}signal:known_bot_data_center`, displayName: 'Known Bot Data Center' },
      { label: `${P}signal:non_browser_user_agent`, displayName: 'Non-Browser User Agent' },
    ],
    dynamicLabels: [
      { prefix: `${P}signal:cloud_service_provider:`, displayName: 'Cloud Service Provider', placeholder: 'aws' },
    ],
  },
  {
    name: 'Targeted Signals',
    labels: [
      { label: `${P}targeted:signal:automated_browser`, displayName: 'Automated Browser (targeted)' },
      { label: `${P}targeted:signal:browser_automation_extension`, displayName: 'Browser Automation Extension' },
      { label: `${P}targeted:signal:browser_inconsistency`, displayName: 'Browser Inconsistency' },
    ],
  },
];

export const namespaceEntries: NamespaceEntry[] = [
  { namespace: `${P}bot:`, displayName: 'All Bot Control labels' },
  { namespace: `${P}bot:category:`, displayName: 'All Bot Categories' },
  { namespace: `${P}bot:name:`, displayName: 'All Bot Names' },
  { namespace: `${P}signal:`, displayName: 'All Signals' },
  { namespace: `${P}targeted:`, displayName: 'All Targeted' },
];

/** Flat list of all static labels for quick lookup */
export const allStaticLabels: LabelEntry[] = labelCategories.flatMap(c => c.labels);
